/* ============================================================
   ENGLISH LANGUAGE — AQA GCSE 8700 (Comberton's English page).
   Paper 1 Explorations in Creative Reading & Writing (1 h 45, 50%)
   Paper 2 Writers' Viewpoints & Perspectives (1 h 45, 50%)
   No tiers — everyone sits the same papers. All extracts below
   are written for this app.
   ============================================================ */
RC.subjects.push({
  id: 'englang', name: 'English Language', emoji: '✍️',
  board: 'AQA GCSE English Language 8700',
  exam: '2 papers, 1 h 45 m each · end of Year 11 (May–June 2027) · same papers for everyone',
  intro: 'Tip: in the exam, the writing question (Q5) is worth HALF of each paper. Easy marks come from good punctuation and paragraphs!',
  units: [
    { id: 'elA', title: 'Know your exams', emoji: '🗺️', blurb: 'Know what every question wants — no surprises on the day.', tag: 'exam', tagText: 'Papers 1 & 2', lessons: [
      LS('el-p1', 'Paper 1 map', '1️⃣', ['Paper 1 = a story extract + YOUR creative writing.', 'Q1 4 marks · Q2 8 · Q3 8 · Q4 20 · Q5 40.'], [
        mc(1, 'Paper 1 reading is based on…', 'An extract from a story (fiction)', ['Two newspaper articles', 'A poem', 'A play script'], 'Paper 1 = Explorations in Creative Reading and Writing. Section A is one fiction extract.'),
        mc(1, 'How long is Paper 1?', '1 hour 45 minutes', ['1 hour', '2 hours 30 minutes', '45 minutes'], 'Both English Language papers are 1 h 45 m.'),
        mc(1, 'Q1 on Paper 1 asks you to…', 'List 4 things from a set part of the text', ['Write a story', 'Compare two texts', 'Analyse structure'], 'Q1 = 4 marks: find 4 true facts in the lines it tells you. Quick marks!'),
        mc(1, 'Which question is the WRITING task?', 'Question 5', ['Question 1', 'Question 3', 'Question 4'], 'Q5 is the writing: 40 marks — half the paper!'),
        mc(2, 'Paper 1 Q5 asks you to write…', 'A description or a story', ['A letter to your MP', 'A speech', 'A summary'], 'Paper 1 Q5 = descriptive OR narrative writing, often with a picture to help.'),
        mc(2, 'Paper 1 Q2 is about…', 'Language — the words and phrases', ['Structure — the order', 'Your opinion of the whole text', 'Spelling'], 'Q2 (8 marks) = how the writer uses LANGUAGE.'),
        mc(2, 'Paper 1 Q3 is about…', 'Structure — how the text is ordered', ['Language', 'Listing facts', 'Writing a story'], 'Q3 (8 marks) = STRUCTURE: beginning, shifts in focus, ending.'),
        mc(2, 'Q5 is worth 40 marks. How many are for spelling, punctuation and grammar?', '16', ['4', '24', '40'], '24 for content and organisation + 16 for technical accuracy (SPaG).'),
        mt(2, 'Match the question to its marks (Paper 1)', [['Q1', '4 marks'], ['Q2 or Q3', '8 marks'], ['Q4', '20 marks'], ['Q5', '40 marks']]),
        mc(3, 'Paper 1 Q4 gives you a statement, like "The ending is tense". You should…', 'Say how far you agree, using evidence', ['Only list facts', 'Write a new ending', 'Correct the spelling'], 'Q4 = EVALUATE: do you agree? Give evidence and explain the writer\'s methods.'),
        mc(3, 'Roughly how long should you spend on Q5?', 'About 45 minutes', ['About 5 minutes', 'About 15 minutes', 'About 1 hour 30 minutes'], 'Q5 is half the marks, so it deserves about 45 minutes — including 5 minutes to plan and 5 to check.'),
        od(3, 'Put Paper 1 in order', ['Read the extract', 'Q1: list 4 things', 'Q2: language', 'Q3: structure', 'Q4: evaluate', 'Q5: creative writing'], 'Reading section first, then writing.'),
      ]),
      LS('el-p2', 'Paper 2 map', '2️⃣', ['Paper 2 = two non-fiction sources + YOUR opinion writing.', 'Q1 4 · Q2 8 · Q3 12 · Q4 16 · Q5 40.'], [
        mc(1, 'Paper 2 reading has…', 'Two non-fiction sources (one old, one modern)', ['One story', 'Three poems', 'A Shakespeare scene'], 'Paper 2 = Writers\' Viewpoints and Perspectives: a 19th-century source + a modern one.'),
        mc(1, 'Paper 2 Q5 asks you to…', 'Give your opinion (e.g. a letter, article or speech)', ['Write a story', 'Describe a picture', 'List 4 things'], 'Paper 2 Q5 = write to present a VIEWPOINT (argue or persuade).'),
        mc(1, 'Paper 2 Q1 asks you to…', 'Shade 4 TRUE statements', ['Write a paragraph', 'Compare sources', 'Write a speech'], 'Q1: 8 statements, shade the 4 true ones. 4 marks.'),
        mc(2, 'Paper 2 Q2 is a…', 'Summary of differences between the two sources', ['Language question', 'Story', 'List'], 'Q2 (8 marks): summarise the DIFFERENCES (e.g. between two people or places).'),
        mc(2, 'Paper 2 Q3 is about…', 'Language in ONE source', ['Both sources\' structure', 'Your own opinion', 'Spelling'], 'Q3 (12 marks): how the writer uses language — one source only.'),
        mc(2, 'Paper 2 Q4 asks you to…', 'Compare the writers\' viewpoints and methods', ['List facts', 'Write a letter', 'Correct mistakes'], 'Q4 (16 marks): COMPARE how both writers feel, and how they show it.'),
        mt(2, 'Match the question to its marks (Paper 2)', [['Q1', '4 marks'], ['Q2', '8 marks'], ['Q3', '12 marks'], ['Q4', '16 marks']]),
        mc(2, 'A "source from the 19th century" was written in…', 'The 1800s', ['The 1900s', 'The 2000s', 'The 1700s'], 'The 19th century = the years 1800–1899. (Confusing, but true!)'),
        mc(3, 'The best comparison words for Q4 are…', 'Whereas, similarly, however', ['Firstly, secondly, lastly', 'Once upon a time', 'In conclusion'], 'Q4 is about comparing — use words that link the two sources.'),
        tf(3, 'In Paper 2 Q2, you should analyse the writer\'s language in detail.', false, 'Q2 is a SUMMARY of differences — say what the differences are and back them up. Language analysis is Q3.'),
        mc(3, 'Besides the 2 papers, there is also a separate…', 'Spoken Language presentation', ['Coursework story', 'Poetry exam', 'Listening test'], 'The Spoken Language endorsement is a short talk. It gets its own grade (Pass, Merit or Distinction).'),
      ]),
    ] },
    { id: 'elB', title: 'Word detective', emoji: '🔎', blurb: 'Spot the technique → name it → say what effect it has. That\'s the language question!', tag: 'exam', tagText: 'P1 Q2 · P2 Q3', lessons: [
      LS('el-tech1', 'Techniques 1', '🕵️', ['Simile = LIKE or AS.  Metaphor = says it IS something.', 'Personification = an object acting like a person.'], [
        mc(1, '"Her smile was as bright as the sun." This is a…', 'Simile', ['Metaphor', 'Alliteration', 'Onomatopoeia'], 'It compares using AS … AS. Similes use "like" or "as".'),
        mc(1, '"The classroom was a zoo." This is a…', 'Metaphor', ['Simile', 'Personification', 'Rhetorical question'], 'It says the classroom IS a zoo (not "like" a zoo) — so it\'s a metaphor.'),
        mc(1, '"The wind howled angrily." This is…', 'Personification', ['A simile', 'Alliteration', 'A fact'], 'Wind can\'t really be angry — it\'s given human feelings. That\'s personification.'),
        mc(1, '"Big brown bears" is an example of…', 'Alliteration', ['Onomatopoeia', 'Simile', 'Hyperbole'], 'Words starting with the same sound (b, b, b) = alliteration.'),
        mc(1, '"Bang! Crash! Sizzle!" These words are…', 'Onomatopoeia', ['Alliteration', 'Metaphors', 'Emotive language'], 'Words that sound like the noise they describe = onomatopoeia.'),
        mt(1, 'Match the technique', [['Simile', 'like / as'], ['Metaphor', 'says it IS'], ['Alliteration', 'same first sound'], ['Onomatopoeia', 'sound words']]),
        mc(2, '"I\'ve told you a million times!" This is…', 'Hyperbole (exaggeration)', ['A fact', 'A simile', 'Personification'], 'Nobody really says it a million times — it\'s exaggerated for effect.'),
        mc(2, '"The sun smiled down on us" makes the day feel…', 'Warm and friendly', ['Scary and dark', 'Boring', 'Cold and sad'], 'Personifying the sun as smiling makes the scene feel happy and welcoming.'),
        mc(2, '"The silence was a heavy blanket." What does this suggest?', 'The silence felt thick and hard to break', ['It was a cold night', 'Someone was asleep', 'The room was loud'], 'The metaphor makes silence feel heavy — like it presses down on everyone.'),
        tf(2, '"He ran like the wind" is a metaphor.', false, 'It uses "like", so it\'s a SIMILE.'),
        mc(3, '"The trees shivered in the cold wind." Best explanation of the effect?', 'It makes the setting feel cold and uneasy, as if even nature is afraid', ['It tells us what type of tree it is', 'It is a simile showing speed', 'It shows the writer likes trees'], 'Good answers explain the FEELING the technique creates for the reader.'),
        mc(3, 'Which is the BEST way to write about a simile in the exam?', 'The simile "as cold as ice" suggests she is unfriendly, making the reader dislike her.', ['There is a simile.', 'The writer uses lots of techniques.', 'Similes are good.'], 'Name it + quote it + explain the effect on the reader. Just spotting it gets few marks.'),
      ]),
      LS('el-tech2', 'Techniques 2', '📣', ['Persuasive tricks: rhetorical questions, rule of three, direct address ("you").', 'Emotive language makes readers feel something.'], [
        mc(1, '"Don\'t you want a better future?" This is a…', 'Rhetorical question', ['Simile', 'Fact', 'Command'], 'A question that doesn\'t need an answer — it makes the reader think.'),
        mc(1, '"It was cold, dark and silent." Three things in a row is called…', 'Rule of three (a list of three)', ['Alliteration', 'Onomatopoeia', 'Repetition'], 'Three things in a list sound complete and powerful.'),
        mc(1, 'Using "you" to speak straight to the reader is…', 'Direct address', ['Hyperbole', 'Metaphor', 'Statistics'], '"You" makes the reader feel involved.'),
        mc(1, '"Innocent, helpless puppies are being abandoned." This uses…', 'Emotive language', ['Onomatopoeia', 'A simile', 'Humour'], 'Words like "innocent" and "helpless" make us feel sad or angry.'),
        mc(2, '"Act now. Sign the petition." These sentences are…', 'Imperatives (commands)', ['Questions', 'Similes', 'Facts'], 'Imperatives tell the reader to DO something.'),
        mc(2, '"9 out of 10 teenagers feel stressed." This is…', 'A statistic', ['An opinion', 'A metaphor', 'Hyperbole'], 'Numbers and facts make an argument sound believable.'),
        mc(2, '"Never. Never. Never give up." This uses…', 'Repetition', ['Rule of three only', 'Onomatopoeia', 'Personification'], 'Repeating a word makes the point stick.'),
        mt(2, 'Match the persuasive trick', [['Rhetorical question', 'Isn\'t it time?'], ['Statistic', '75% agree'], ['Imperative', 'Stop this now!'], ['Direct address', 'You deserve better']]),
        mc(2, 'In the AFOREST memory trick for persuasive writing, the "E" stands for…', 'Emotive language', ['Ending', 'Examples only', 'Exclamation marks'], 'A-F-O-R-E-S-T: Alliteration, Facts, Opinions, Rhetorical questions, Emotive language, Statistics, Three (rule of three).'),
        mc(3, 'Why might a writer use a short sentence like "Then silence."?', 'To create tension and make the moment stand out', ['Because they ran out of ideas', 'To explain a fact', 'To make it funny'], 'Short sentences slow the reader down and add drama.'),
        mc(3, 'A writer uses lots of words about fire: "blazing", "scorching", "burning". This pattern is called…', 'A semantic field', ['A simile', 'A rhetorical question', 'Onomatopoeia'], 'A semantic field = a group of words linked to the same topic. It builds a strong mood.'),
      ]),
      LS('el-words', 'Types of words', '🧩', ['Noun = thing.  Verb = doing word.  Adjective = describes a noun.  Adverb = describes a verb.'], [
        mc(1, 'In "The dog barked", which word is the VERB?', 'barked', ['The', 'dog', 'None'], 'A verb is an action/doing word.'),
        mc(1, 'In "a gloomy house", which word is the ADJECTIVE?', 'gloomy', ['a', 'house', 'None'], 'An adjective describes a noun (the house).'),
        mc(1, 'Which of these is a NOUN?', 'castle', ['quickly', 'run', 'beautiful'], 'A noun is a person, place or thing.'),
        mc(2, 'In "She crept silently", which word is the ADVERB?', 'silently', ['She', 'crept', 'None'], 'Adverbs describe HOW something is done — they often end in -ly.'),
        mt(2, 'Match the word type', [['Noun', 'forest'], ['Verb', 'sprinted'], ['Adjective', 'enormous'], ['Adverb', 'nervously']]),
        mc(2, 'Why might a writer choose the verb "slammed" instead of "closed"?', 'It shows anger and makes a loud, sudden image', ['It is shorter', 'It is a noun', 'It is more polite'], 'Strong verbs show feelings. "Slammed" = anger/force.'),
        mc(3, 'A "first person" narrator uses…', 'I and we', ['He and she', 'You', 'They only'], 'First person = "I". Third person = "he/she/they".'),
        mc(3, 'The word "whispered" suggests…', 'Secrecy or fear', ['Anger', 'Excitement', 'Boredom'], 'Whispering suggests someone doesn\'t want to be heard.'),
        mc(3, 'In the exam, talking about the word classes a writer uses (like verbs or adjectives) is…', 'A good way to get higher language marks', ['Not allowed', 'Only for Q1', 'Only for poetry'], 'Naming word types (e.g. "the verb \'lurched\'") shows precise analysis.'),
      ]),
    ] },
    { id: 'elC', title: 'Structure', emoji: '🏗️', blurb: 'How a writer ORDERS a text to keep you reading.', tag: 'exam', tagText: 'P1 Q3', lessons: [
      LS('el-struct', 'Structure spotting', '🧱', ['Structure = the ORDER: what we see first, what changes, how it ends.', 'Look for shifts in focus, flashbacks, and a change of mood.'], [
        mc(1, 'Structure questions are about…', 'The order and shape of the text', ['Spelling', 'Similes only', 'The writer\'s life'], 'Structure = how the text is put together from start to finish.'),
        mc(1, 'A "flashback" is when…', 'The story jumps back in time', ['The story ends', 'Someone takes a photo', 'The weather changes'], 'A flashback shows something from the past.'),
        mc(1, 'Starting with a wide view of a town, then zooming in on one house, is…', 'Narrowing the focus (zooming in)', ['A flashback', 'Alliteration', 'A summary'], 'Like a film camera: wide shot → close-up.'),
        mc(2, 'A "cyclical" structure means…', 'The ending links back to the beginning', ['It is about bikes', 'It has no ending', 'Every paragraph is the same length'], 'Cyclical = goes round in a circle: it ends where it started.'),
        mc(2, 'Foreshadowing is…', 'A hint about what will happen later', ['A description of shadows', 'A type of rhyme', 'The last line'], 'Foreshadowing builds suspense.'),
        mc(2, 'A one-sentence paragraph is often used to…', 'Create impact or tension', ['Save paper', 'Start a list', 'Show a flashback'], 'It stands out on its own and grabs attention.'),
        mt(2, 'Match the structure feature', [['Flashback', 'back in time'], ['Foreshadowing', 'hint of the future'], ['Shift in focus', 'moves to new thing'], ['Cyclical', 'ends where it began']]),
        mc(3, 'Which is a STRUCTURE point, not a language point?', 'The writer moves from the storm outside to the boy inside', ['The simile "like a wolf"', 'The adjective "gloomy"', 'Alliteration in "silent sea"'], 'Movement/shifts in focus are structure. Techniques in single phrases are language.'),
        mc(3, 'Good words for a structure answer are…', 'At the start… then the focus shifts… by the end…', ['Firstly, the simile…', 'I think the writer is clever', 'The spelling is good'], 'Track the text through time: beginning → middle → end.'),
        mc(3, 'Why might a writer end on a cliffhanger?', 'To leave the reader wanting to know what happens next', ['To finish neatly', 'Because the story is over', 'To explain everything'], 'Cliffhangers keep tension going.'),
      ]),
    ] },
    { id: 'elD', title: 'Reading questions', emoji: '📖', blurb: 'Practise the exact question types, on mini extracts.', tag: 'exam', tagText: 'Section A', lessons: [
      LS('el-find', 'Find the facts (Q1)', '🗂️', ['Only use the lines they tell you.', 'Copy short, clear facts. No need to explain.'], [
        xq(1, 'The café was small and warm. A red door stood at the front. Inside, an old man was reading a newspaper by the window.', 'Which is TRUE?', 'The door was red', ['The café was huge', 'The man was young', 'The man was cooking'], 'The extract says "A red door stood at the front".'),
        xq(1, 'The café was small and warm. A red door stood at the front. Inside, an old man was reading a newspaper by the window.', 'What was the old man doing?', 'Reading a newspaper', ['Sleeping', 'Serving coffee', 'Painting the door'], '"reading a newspaper by the window".'),
        xq(1, 'Maya pulled her coat tighter. Snow had covered the car park, and her breath made little clouds. The bus was late again.', 'Which is TRUE?', 'The bus was late', ['It was a hot day', 'Maya had no coat', 'The car park was empty of snow'], '"The bus was late again."'),
        xq(2, 'Maya pulled her coat tighter. Snow had covered the car park, and her breath made little clouds. The bus was late again.', 'The word "again" suggests…', 'The bus is often late', ['The bus is never late', 'Maya likes waiting', 'It is Maya\'s first day'], '"Again" tells us this has happened before.'),
        xq(2, 'The lighthouse had not shone for twenty years. Its paint peeled like old skin, and gulls nested in the broken windows.', 'Which is TRUE?', 'Birds lived in the windows', ['The light still worked', 'It was freshly painted', 'It was built last year'], '"gulls nested in the broken windows".'),
        xq(2, 'The lighthouse had not shone for twenty years. Its paint peeled like old skin, and gulls nested in the broken windows.', 'What does the simile "like old skin" suggest?', 'The lighthouse is old and falling apart', ['It is brand new', 'It is painted pink', 'It is warm'], 'Comparing peeling paint to old skin makes it seem aged and decaying.'),
        tf(2, 'In Paper 1 Q1, you should include facts from ANYWHERE in the source.', false, 'Only use the lines the question tells you — facts from elsewhere get no marks.'),
        xq(3, 'Tom smiled at the teacher, but under the desk his hands were shaking. He had not done the homework. Again.', 'What can you INFER about Tom?', 'He is nervous and hiding it', ['He is calm and confident', 'He loves homework', 'He is angry with the teacher'], 'The smile hides his shaking hands — he is pretending to be fine. That\'s inference: reading between the lines.'),
        xq(3, 'The new estate was all glass and gleaming white walls. Nobody said hello. Every curtain stayed closed.', 'What impression do we get of the estate?', 'It looks perfect but feels unfriendly', ['It is dirty and old', 'Everyone is very friendly', 'It is noisy'], '"Gleaming" = looks good. "Nobody said hello" + closed curtains = cold and unwelcoming.'),
      ]),
      LS('el-lang', 'Language answers', '🔬', ['Use W-H-Y: WHAT the writer does (quote) → HOW (technique) → WHY (effect on reader).'], [
        mc(1, 'In a language answer you must use…', 'Short quotes from the text', ['Your own story', 'Long copied paragraphs', 'No evidence'], 'Short, precise quotes are best — just the key words.'),
        mc(1, 'What does "effect on the reader" mean?', 'What the reader thinks or feels because of the words', ['How long the text is', 'Who the writer is', 'The spelling'], 'Always explain what the words make the reader think, feel or imagine.'),
        od(2, 'Put this language answer in a good order', ['The writer uses the verb "crept"', 'This suggests the boy is moving slowly and secretly', 'It makes the reader feel tense about being caught'], 'WHAT (quote) → HOW/suggests → WHY (effect).'),
        mc(2, 'Which sentence starter is best for explaining?', 'This suggests that…', ['The end.', 'Once upon a time…', 'I don\'t know but…'], '"This suggests…", "This shows…", "This makes the reader…" are great explaining phrases.'),
        xq(2, 'The storm tore at the roof, screaming through every gap.', 'Which technique is in "screaming"?', 'Personification', ['Simile', 'Statistic', 'Rhetorical question'], 'A storm can\'t really scream — it\'s made to sound like a person.'),
        xq(2, 'The storm tore at the roof, screaming through every gap.', 'What is the effect of "tore" and "screaming"?', 'The storm feels violent and frightening', ['The storm feels gentle', 'It makes it sound funny', 'It shows it is summer'], 'Violent verbs make the storm sound dangerous and alive.'),
        mc(3, 'Which is the strongest analysis?', '"Crawled" suggests time passing painfully slowly, which builds the reader\'s boredom and frustration.', ['"Crawled" is a verb.', 'The writer uses good words.', 'There is a lot of description.'], 'Zoom in on ONE word and explain what it suggests + the effect.'),
        mc(3, 'You can get more marks by…', 'Explaining more than one meaning a word could have', ['Writing about spelling', 'Retelling the story', 'Using no quotes'], 'Exploring different interpretations ("this could also suggest…") shows higher-level thinking.'),
      ]),
      LS('el-comp', 'Evaluate & compare', '⚖️', ['Evaluate (P1 Q4): how far do you agree? Give evidence.', 'Compare (P2 Q4): whereas / similarly / however.'], [
        mc(1, 'Which word shows you are COMPARING?', 'Whereas', ['Because', 'Firstly', 'Suddenly'], '"Whereas", "however", "similarly", "on the other hand" link two sources.'),
        mc(1, '"Similarly" shows two things are…', 'Alike', ['Different', 'Wrong', 'Funny'], 'Similarly = in the same way.'),
        mc(1, '"However" shows…', 'A difference or contrast', ['Something is the same', 'The end', 'A question'], 'However = but / on the other hand.'),
        mc(2, 'P1 Q4 says: "In this part, the writer makes the house seem terrifying." A good start is…', 'I mostly agree, because the writer describes the "rotting" door…', ['I like houses.', 'The story is about a house.', 'No.'], 'Say how far you agree, then prove it with evidence and methods.'),
        xq(2, 'Source A (1850): "Children of eight work fourteen hours in the mill, and are thankful for it."\nSource B (2024): "Teenagers today say they feel overworked by homework."', 'What is the BIG difference?', 'Source A\'s children do far harder work than Source B\'s teenagers', ['Both are about holidays', 'Both are happy', 'Source B children work in mills'], 'A summary of differences picks out the key contrast, with evidence from both.'),
        mc(2, 'A "viewpoint" or "perspective" means…', 'What the writer thinks or feels about the topic', ['The view out of a window', 'The number of paragraphs', 'The title'], 'Paper 2 Q4 asks how the writers\' views are the same or different.'),
        mc(3, 'For P2 Q4, you must compare…', 'The writers\' views AND the methods they use to show them', ['Only the dates', 'Only spelling', 'Only the titles'], 'What they think + how they show it (tone, language, structure).'),
        mc(3, 'A writer\'s "tone" could be described as…', 'Angry, hopeful, sarcastic or worried', ['Long or short', 'Blue or red', 'Fact or fiction'], 'Tone = the attitude or mood of the writing. Naming the tone is great for comparison questions.'),
      ]),
    ] },
    { id: 'elE', title: 'Your writing (Q5)', emoji: '🖊️', blurb: 'Half the marks on each paper. Plan it, paragraph it, check it.', tag: 'exam', tagText: '40 marks each', lessons: [
      LS('el-desc', 'Describing & stories', '🎨', ['Use your 5 senses: see, hear, smell, touch, taste.', 'Show, don\'t tell: "her hands shook" beats "she was scared".'], [
        mc(1, 'Which uses the sense of SMELL?', 'The air was thick with burnt toast', ['The sky was grey', 'A dog barked', 'The wall was rough'], 'Burnt toast = something you smell.'),
        mc(1, '"Show, don\'t tell" means…', 'Show a feeling through actions and details', ['Draw pictures', 'Write only dialogue', 'Tell the reader the ending first'], '"His fists clenched" SHOWS anger better than "he was angry".'),
        mc(1, 'Which sentence SHOWS nervousness?', 'Her knee bounced under the table and she chewed her pen', ['She was nervous', 'She felt a bit nervous', 'Nervous is a feeling'], 'Actions and details let the reader work it out.'),
        mc(2, 'Descriptive writing mostly needs…', 'Lots of detail about ONE moment or place', ['A long plot with many events', 'Only speech', 'Lists of facts'], 'Description = zoom in on a moment; a story = events that happen.'),
        od(2, 'Order a simple story plan (5 parts)', ['Opening: set the scene', 'Build-up: something starts', 'Problem: it goes wrong', 'Resolution: it is sorted', 'Ending: how things are now'], 'Five parts keep your story clear and finished.'),
        mc(2, 'A good way to open a story is…', 'Start in the middle of the action', ['"One day I woke up and had breakfast."', 'Explain the whole plot first', 'Start with "The end"'], 'Dropping the reader into action grabs attention.'),
        mc(2, 'How many main characters is best for a 45-minute story?', '1 or 2', ['10', '0', 'As many as possible'], 'Keep it small so you can make it detailed.'),
        mc(3, 'Which opening is the most effective?', 'The phone buzzed at 3am. Nobody ever called at 3am.', ['Hello, my name is Sam and this is my story.', 'It was a normal day.', 'I am going to write about a phone.'], 'Mystery and a short sentence make the reader curious.'),
        mc(3, 'Varying sentence lengths helps because…', 'Short sentences create tension; long ones build description', ['It fills the page', 'Examiners like long words only', 'It is required by law'], 'Mix them up for effect — that earns marks for "crafting".'),
        mc(3, 'A good ending for a description could…', 'Link back to the opening (cyclical)', ['Just stop mid-sentence', 'Say "and then I woke up, it was a dream"', 'Repeat the question'], 'A cyclical ending feels crafted and complete. Avoid "it was all a dream"!'),
      ]),
      LS('el-view', 'Opinion writing', '📢', ['Paper 2 Q5: letter, article, speech or leaflet.', 'Plan: intro → 3 or 4 points → conclusion. Use AFOREST.'], [
        mc(1, 'A formal letter starts with…', 'Dear Sir or Madam,', ['Hiya!', 'Yo', 'To whoever'], 'Formal letters: "Dear Sir/Madam" (end "Yours faithfully") or "Dear Mrs Smith" (end "Yours sincerely").'),
        mc(1, 'A speech should…', 'Speak directly to the audience ("you", "we")', ['Have a headline', 'Start with "Dear Sir"', 'Be in bullet points'], 'Speeches talk to listeners: "Good morning, everyone…"'),
        mc(1, 'An article needs a…', 'Headline', ['Signature', 'Greeting', 'Stage directions'], 'Articles have a headline (and maybe a subheading).'),
        mt(2, 'Match the form to its feature', [['Letter', 'Dear…'], ['Article', 'Headline'], ['Speech', 'Thank you for listening'], ['Leaflet', 'Subheadings']]),
        mc(2, 'A "counter-argument" is…', 'Mentioning the other side, then proving it wrong', ['Arguing with the examiner', 'A shop counter', 'Repeating your point'], '"Some people say… however…" makes your argument stronger.'),
        mc(2, 'Which is the best persuasive sentence?', 'Surely every child deserves a safe place to play?', ['Parks are fine I guess.', 'Some people like parks.', 'Parks exist.'], 'A rhetorical question + emotive words ("deserves", "safe").'),
        od(2, 'Order an opinion piece', ['Hook the reader + say your view', 'Point 1 with evidence', 'Point 2 with evidence', 'Counter-argument', 'Strong conclusion'], 'Plan it before writing — 5 minutes of planning saves marks.'),
        mc(3, 'How should you end a persuasive piece?', 'With a powerful call to action or final question', ['With "that\'s it"', 'With a new topic', 'With no ending'], 'e.g. "Act now — before it\'s too late."'),
        mc(3, 'Who is your "audience" in a letter to your headteacher?', 'The headteacher — so be polite and formal', ['Your best friend — so use slang', 'Young children', 'Nobody'], 'Always match your tone to the audience and purpose.'),
      ]),
    ] },
    { id: 'elF', title: 'Spelling, punctuation & grammar', emoji: '🔤', blurb: 'SPaG is 16 marks on EACH paper. Tidy mistakes cost marks — this unit wins them back.', tag: 'exam', tagText: '32 marks', lessons: [
      LS('el-punc', 'Punctuation', '❗', ['Every sentence: Capital letter at the start, full stop at the end.', 'Don\'t join two sentences with just a comma.'], [
        mc(1, 'Which sentence is correct?', 'We went to London. It was busy.', ['we went to London. it was busy.', 'We went to London, it was busy.', 'We went to london it was busy'], 'Two sentences → two full stops (or use "and"/"but"). A comma alone can\'t join them.'),
        mc(1, 'Names of people and places need…', 'A capital letter', ['A full stop', 'A comma', 'An apostrophe'], 'Proper nouns: Chloe, Cambridge, Monday, Tesco.'),
        mc(1, 'Which ends a question?', '?', ['.', ',', '!'], 'Questions end with a question mark.'),
        mc(2, 'Which uses an apostrophe correctly to show belonging?', "The dog's bone", ["The dogs' bone (one dog)", "The dog,s bone", "The do'gs bone"], "One dog owns it → dog's."),
        mc(2, '"It\'s" means…', 'It is (or it has)', ['Belonging to it', 'Its plural', 'Nothing'], "It's = it is. \"Its\" (no apostrophe) = belonging: \"The dog wagged its tail.\""),
        mc(2, 'Which is correct?', "The cat licked its paw.", ["The cat licked it's paw.", "The cat licked its' paw.", "The cat licked i'ts paw."], 'Belonging = its (no apostrophe).'),
        mc(2, 'Which is correct?', "I can't come today.", ["I ca'nt come today.", "I cant' come today.", "I can,t come today."], "The apostrophe goes where the letters are missing: can not → can't."),
        mc(3, 'Where does the colon go? "You need three things __ pen, paper and ideas."', ':', [';', ',', '!'], 'A colon (:) introduces a list or explanation.'),
        mc(3, 'Which uses a semicolon correctly?', 'It was late; everyone had gone home.', ['It was; late everyone had gone home.', 'It; was late.', 'It was late everyone; had gone home.'], 'A semicolon joins two full, linked sentences.'),
        mc(3, 'Which punctuation creates a dramatic pause?', 'An ellipsis (…)', ['A full stop only', 'A comma in a list', 'Brackets'], 'Using a range of punctuation (… : ; ! ?) earns top SPaG marks — used correctly!'),
      ]),
      LS('el-homo', 'Tricky word pairs', '🔀', ['There = place. Their = belonging. They\'re = they are.', 'Your = belonging. You\'re = you are.'], [
        mc(1, '___ going to the cinema.', "They're", ['Their', 'There'], "They're = they are."),
        mc(1, 'Put the bags over ___.', 'there', ['their', "they're"], 'There = a place (it has "here" in it!).'),
        mc(1, 'They forgot ___ coats.', 'their', ['there', "they're"], 'Their = belonging to them.'),
        mc(1, '___ my best friend.', "You're", ['Your'], "You're = you are."),
        mc(2, 'I want to come ___.', 'too', ['to', 'two'], 'Too = also / too much. Two = 2. To = direction (go to school).'),
        mc(2, '___ were you last night?', 'Where', ['Were', 'Wear', "We're"], 'Where = a place question. Were = past of "are". Wear = clothes.'),
        mc(2, 'We ___ late for school.', 'were', ['where', 'wear'], '"We were late."'),
        mc(2, 'I should ___ gone.', 'have', ['of'], '"Should have" — never "should of"!'),
        mc(3, 'The noise will ___ the baby.', 'affect', ['effect'], 'Affect is usually the verb (action). Effect is usually the noun (result).'),
        mc(3, 'That film had a big ___ on me.', 'effect', ['affect'], 'Effect = the result (noun).'),
        mc(3, 'Choose the correct pair: "I ___ my keys, so I was ___ for school."', 'lost … late', ['loose … late', 'lose … lately', 'loosed … late'], 'Lost = past of lose. Loose = not tight.'),
      ]),
      LS('el-spell', 'Spelling traps', '🐝', ['Break long words into chunks: be-cause, def-in-ite-ly.', 'Tricks help: "a piece of pie".'], [
        mc(1, 'Which spelling is right?', 'because', ['becuase', 'becos', 'beacuse'], 'Trick: Big Elephants Can Always Understand Small Elephants.'),
        mc(1, 'Which spelling is right?', 'friend', ['freind', 'frend', 'friened'], 'Trick: a FRIend to the END — fri + end.'),
        mc(1, 'Which spelling is right?', 'beautiful', ['beutiful', 'beatiful', 'beautifull'], 'Chunks: b-eau-ti-ful. "-ful" has one L.'),
        mc(2, 'Which spelling is right?', 'definitely', ['definately', 'defiantly', 'definetly'], 'It has "finite" in the middle: de-FINITE-ly.'),
        mc(2, 'Which spelling is right?', 'separate', ['seperate', 'seprate', 'separete'], 'There is "a rat" in sepARATe.'),
        mc(2, 'Which spelling is right?', 'believe', ['beleive', 'belive', 'beleave'], 'Never beLIEve a LIE.'),
        mc(2, 'Which spelling is right?', 'necessary', ['neccessary', 'necesary', 'neccesary'], 'One Collar, two Sleeves: 1 c, 2 s.'),
        mc(3, 'Which spelling is right?', 'embarrass', ['embarass', 'embaress', 'embarras'], 'Double r, double s — you go Really Red and Smile Shyly.'),
        mc(3, 'Which spelling is right?', 'environment', ['enviroment', 'enviorment', 'envirement'], 'There is IRON in envIRONment.'),
        mc(3, 'Which spelling is right?', 'business', ['buisness', 'busness', 'bussiness'], 'Chunk it: BUS-I-NESS.'),
      ]),
      LS('el-sent', 'Sentence types', '🧵', ['Simple: one idea.  Compound: two ideas + and/but/so.  Complex: extra bit that can\'t stand alone.'], [
        mc(1, '"The dog barked." is a…', 'Simple sentence', ['Compound sentence', 'Complex sentence', 'Question'], 'One main idea = simple.'),
        mc(1, '"The dog barked and the cat ran." is a…', 'Compound sentence', ['Simple sentence', 'Complex sentence', 'Command'], 'Two ideas joined with "and" = compound.'),
        mc(2, '"Although it was raining, we went out." is a…', 'Complex sentence', ['Simple sentence', 'Compound sentence', 'List'], '"Although it was raining" can\'t stand alone — that makes it complex.'),
        mc(2, 'Which word can start a complex sentence?', 'Although', ['And', 'The', 'Yes'], 'Although, because, when, if, while, since…'),
        mc(2, 'Starting sentences in different ways is good because…', 'It keeps writing interesting (and gets marks)', ['It is shorter', 'It avoids full stops', 'It is required'], 'Try starting with a verb ("Running…"), an adverb ("Slowly,…") or a sound.'),
        mc(3, 'Which sentence starts with an -ing verb?', 'Shivering, she opened the door.', ['She shivered and opened the door.', 'The door opened.', 'It was cold.'], 'Starting with an -ing verb adds variety.'),
        mc(3, 'Which is a "fronted adverbial"?', 'Before dawn, the town was silent.', ['The town was silent before dawn.', 'The town was silent.', 'Silent town.'], 'A fronted adverbial puts when/where/how at the START, followed by a comma.'),
        tf(3, 'Using only very short sentences all the way through is the best way to get top marks.', false, 'Variety is the key: mix short, medium and long sentences.'),
      ]),
    ] },
  ],
});
