/* ============================================================
   ENGLISH LITERATURE — AQA GCSE 8702.
   Comberton's GCSE English Q&A says teachers choose set texts per
   class, so Chloe picks her books. Only the most common AQA choices
   are included. Quotes are kept short.
   Paper 1: Shakespeare + 19th-century novel (1 h 45)
   Paper 2: Modern text + anthology poetry + unseen poetry (2 h 15)
   ============================================================ */
RC.books = [
  { id: 'macbeth', group: 'shakes', name: 'Macbeth', by: 'William Shakespeare', emoji: '🗡️' },
  { id: 'rj', group: 'shakes', name: 'Romeo and Juliet', by: 'William Shakespeare', emoji: '💘' },
  { id: 'acc', group: 'novel', name: 'A Christmas Carol', by: 'Charles Dickens', emoji: '👻' },
  { id: 'jh', group: 'novel', name: 'Jekyll and Hyde', by: 'Robert Louis Stevenson', emoji: '🧪' },
  { id: 'aic', group: 'modern', name: 'An Inspector Calls', by: 'J. B. Priestley', emoji: '🕵️' },
  { id: 'pc', group: 'poetry', name: 'Power and Conflict poems', by: 'AQA anthology — 15 poems', emoji: '⚔️' },
];
RC.subjects.push({
  id: 'englit', name: 'English Literature', emoji: '📚',
  board: 'AQA GCSE English Literature 8702',
  exam: 'Paper 1 (1 h 45) + Paper 2 (2 h 15) · May–June 2027 · closed book — no copies of the texts!',
  intro: 'The exams are CLOSED BOOK — so knowing the story, the characters and a few short quotes is the secret weapon.',
  units: [
    { id: 'lA', title: 'Know your exams', emoji: '🗺️', blurb: 'What\'s in each paper.', tag: 'exam', tagText: 'Papers 1 & 2', lessons: [
      LS('lit-exam', 'Lit exam map', '🗺️', ['Paper 1 = Shakespeare + 19th-century novel.', 'Paper 2 = modern text + poems + unseen poems.'], [
        mc(1, 'Can you take your books into the Literature exams?', 'No — it\'s closed book', ['Yes, any copy', 'Only the poems', 'Only a revision guide'], 'Closed book: you get a short extract, but you need to know the rest yourself.'),
        mc(1, 'Paper 1 is about…', 'Shakespeare and a 19th-century novel', ['Poetry only', 'A modern play only', 'Non-fiction'], 'Paper 1: Section A Shakespeare, Section B the 19th-century novel.'),
        mc(1, 'Paper 2 includes…', 'A modern text, anthology poems and unseen poems', ['Shakespeare', 'A 19th-century novel', 'A spelling test'], 'Paper 2: modern text, your poetry cluster, and poems you\'ve never seen.'),
        mc(2, 'In the Shakespeare question you get…', 'An extract, then write about the whole play too', ['The whole play to read', 'No extract', 'A poem'], 'Start with the extract, then link to other parts of the play.'),
        mc(2, '"Context" means…', 'What was happening when the text was written', ['The number of pages', 'The title', 'The exam board'], 'e.g. Victorian poverty for A Christmas Carol, or King James I for Macbeth.'),
        mc(2, 'Which two questions have extra marks for SPaG?', 'Shakespeare and the modern text', ['Both poetry questions', 'The novel and unseen poem', 'None'], 'Those two essays get 4 extra marks each for spelling, punctuation and grammar.'),
        mc(3, 'For the anthology poetry question, you must…', 'Compare the named poem with one other from your cluster', ['Write about all 15 poems', 'Write a new poem', 'Only write about the named poem'], 'You get one poem printed; you choose a second one from memory to compare.'),
        mc(3, 'How long is Paper 2?', '2 hours 15 minutes', ['1 hour 45 minutes', '1 hour', '3 hours'], 'Paper 1 = 1 h 45. Paper 2 = 2 h 15.'),
        mc(3, 'In a Lit essay, the best quotes are…', 'Short — just a few key words', ['Whole pages', 'Invented', 'Never used'], 'Short quotes are easier to remember AND easier to analyse.'),
      ]),
      LS('lit-poetry-tools', 'Poetry toolkit (unseen)', '🧰', ['Stanza = a verse (like a paragraph in a poem).', 'Speaker = the voice in the poem.  Tone = its mood.'], [
        mc(1, 'A "stanza" is…', 'A group of lines in a poem (a verse)', ['A type of rhyme', 'The poet\'s name', 'The title'], 'Stanzas are the "paragraphs" of a poem.'),
        mc(1, 'Words that end with the same sound (cat / hat) are…', 'Rhymes', ['Similes', 'Stanzas', 'Metaphors'], 'Rhyme can make a poem feel musical or neat.'),
        mc(1, 'The "speaker" of a poem is…', 'The voice telling the poem', ['The reader', 'The examiner', 'The publisher'], 'The speaker isn\'t always the poet.'),
        mc(2, 'A sentence that runs on to the next line without punctuation is…', 'Enjambment', ['Caesura', 'Rhyme', 'A stanza'], 'Enjambment can make thoughts spill over or speed up.'),
        mc(2, 'A pause in the MIDDLE of a line (like a full stop) is…', 'Caesura', ['Enjambment', 'Rhyme', 'Rhythm'], 'Caesura makes the reader stop — often for shock or sadness.'),
        mc(2, 'A poem with 14 lines, often about love, is a…', 'Sonnet', ['Limerick', 'Haiku', 'Ballad'], 'Sonnets have 14 lines.'),
        mt(2, 'Match the poetry word', [['Stanza', 'verse'], ['Enjambment', 'runs on'], ['Caesura', 'mid-line pause'], ['Tone', 'mood']]),
        mc(3, 'A poem with no regular rhyme or rhythm is…', 'Free verse', ['A sonnet', 'A limerick', 'A couplet'], 'Free verse can feel like natural speech — or like chaos.'),
        mc(3, 'A "volta" is…', 'A turning point where the poem\'s mood or idea changes', ['The final word', 'A rhyme', 'The poet\'s signature'], 'Look for words like "but" or "yet" — the poem often turns there.'),
        mc(3, 'For an unseen poem, the first thing to work out is…', 'What it\'s about and how the speaker feels', ['Every technique in it', 'How many syllables there are', 'Who published it'], 'Meaning first, then methods. That makes your answer make sense.'),
      ]),
    ] },
    /* ---------------- MACBETH ---------------- */
    { id: 'lMac', book: 'macbeth', title: 'Macbeth', emoji: '🗡️', blurb: 'A brave soldier + a prophecy + ambition = murder, guilt and doom.', tag: 'exam', tagText: 'Paper 1', lessons: [
      LS('mac-plot', 'Macbeth: the story', '📜', ['Witches → prophecy → Duncan murdered → Banquo murdered → Macduff\'s family murdered → Macbeth killed.'], [
        mc(1, 'Who does Macbeth meet at the very start?', 'Three witches', ['King Duncan', 'A ghost', 'Macduff'], 'The witches predict that Macbeth will be king.'),
        mc(1, 'Who does Macbeth murder to become king?', 'King Duncan', ['Banquo', 'Malcolm', 'Macduff'], 'He kills Duncan in his sleep, at Macbeth\'s own castle.'),
        mc(1, 'Who pushes Macbeth to kill the king?', 'Lady Macbeth', ['Banquo', 'The Porter', 'Fleance'], 'She questions his manhood until he agrees.'),
        mc(1, 'What happens to Macbeth at the end?', 'Macduff kills him', ['He becomes a hero', 'He runs away to England', 'He lives happily'], 'Macduff beheads him, and Malcolm becomes king.'),
        od(2, 'Put these events in order', ['The witches\' prophecy', 'Duncan is murdered', 'Banquo is murdered', 'Macduff\'s family is killed', 'Macbeth is killed'], 'Each murder makes the next one feel easier to Macbeth.'),
        mc(2, 'Whose ghost does Macbeth see at the banquet?', 'Banquo\'s', ['Duncan\'s', 'Lady Macbeth\'s', 'Macduff\'s'], 'Banquo\'s ghost shows Macbeth\'s guilt and fear.'),
        mc(2, 'Who escapes when Banquo is killed?', 'Fleance, his son', ['Malcolm', 'Lady Macbeth', 'Duncan'], 'The witches said Banquo\'s children would be kings — so Fleance escaping worries Macbeth.'),
        mc(2, 'What happens to Lady Macbeth?', 'She sleepwalks, full of guilt, and dies', ['She becomes queen forever', 'She kills Macduff', 'She moves to England'], '"Out, damned spot!" — she tries to wash invisible blood off her hands.'),
        mc(3, 'The witches say Macbeth is safe until…', 'Birnam Wood comes to Dunsinane', ['The sun rises', 'Banquo returns', 'He leaves Scotland'], 'Malcolm\'s army carries branches from Birnam Wood — so the "wood" really moves!'),
        mc(3, 'Why can Macduff kill Macbeth, even though "none of woman born" could harm him?', 'He was born by caesarean ("untimely ripped")', ['He is a ghost', 'He is a witch', 'He is Duncan\'s son'], 'The witches\' promise was a trick — a theme of equivocation (double meanings).'),
      ]),
      LS('mac-chars', 'Macbeth: characters', '👑', ['Macbeth: brave → ambitious → tyrant.', 'Lady Macbeth: powerful → guilty → dead.'], [
        mt(1, 'Match the character', [['Macbeth', 'kills the king'], ['Duncan', 'the good king'], ['Banquo', 'loyal friend'], ['Macduff', 'kills Macbeth']]),
        mc(1, 'At the start, Macbeth is described as…', '"brave Macbeth" — a hero in battle', ['A coward', 'A king', 'A witch'], 'He starts as a loyal war hero — which makes his fall more shocking.'),
        mc(2, 'How does Lady Macbeth change?', 'From strong and controlling to full of guilt', ['From guilty to happy', 'She doesn\'t change', 'From queen to witch'], 'She starts in control but ends broken by guilt.'),
        mc(2, 'Banquo is a contrast (foil) to Macbeth because…', 'He hears the prophecy too but doesn\'t act on it', ['He kills the king first', 'He is a witch', 'He is Macbeth\'s brother'], 'Banquo shows the choice Macbeth COULD have made.'),
        mc(2, 'Malcolm is…', 'Duncan\'s son, who becomes king at the end', ['Macbeth\'s son', 'A witch', 'The porter'], 'Order is restored when the rightful heir takes the throne.'),
        mc(3, 'By the end, Malcolm calls Macbeth and his wife…', '"this dead butcher and his fiend-like queen"', ['"brave heroes"', '"poor victims"', '"noble friends"'], 'This shows how far they have fallen.'),
        mc(3, 'Who is most to blame for Duncan\'s death? A strong answer would…', 'Weigh up Macbeth, Lady Macbeth and the witches, then decide', ['Just say "the witches"', 'Say nobody', 'Only retell the plot'], 'Exam questions reward a clear argument that considers different views.'),
      ]),
      LS('mac-quotes', 'Macbeth: key quotes', '💬', ['Learn a few SHORT quotes really well.', 'Say who said it and what it shows.'], [
        mc(1, '"Fair is foul, and foul is fair" is said by…', 'The witches', ['Macbeth', 'Duncan', 'Lady Macbeth'], 'It means things are not what they seem — good and bad are mixed up.'),
        mc(1, '"Out, damned spot!" is said by…', 'Lady Macbeth', ['Macbeth', 'Banquo', 'The witches'], 'While sleepwalking — she can\'t wash off her guilt.'),
        mc(2, '"Is this a dagger which I see before me" shows Macbeth is…', 'Imagining things before the murder', ['Happy', 'Cooking', 'Already king'], 'His mind is troubled — he sees a floating dagger.'),
        mc(2, '"Look like th\'innocent flower, / But be the serpent under\'t" means…', 'Look innocent but be dangerous underneath', ['Plant flowers', 'Be kind to snakes', 'Tell the truth'], 'Lady Macbeth\'s advice — appearance vs reality.'),
        mc(2, '"Stars, hide your fires; / Let not light see my black and deep desires" shows…', 'Macbeth wants to hide his evil thoughts', ['He loves astronomy', 'He is afraid of the dark', 'He wants a party'], 'Light = good; darkness = evil. He wants his ambition hidden.'),
        mc(3, '"O, full of scorpions is my mind" shows…', 'Macbeth\'s mind is tortured and dangerous', ['He has a pet', 'He is calm', 'He is bored'], 'Scorpions = pain, poison, restlessness.'),
        mc(3, '"Unsex me here" — Lady Macbeth wants to…', 'Lose her female softness so she can do evil', ['Become a man legally', 'Go to sleep', 'Leave Scotland'], 'She rejects the idea that women must be gentle.'),
        mc(3, '"Tomorrow, and tomorrow, and tomorrow" is Macbeth\'s speech after…', 'Hearing Lady Macbeth is dead', ['Killing Duncan', 'Meeting the witches', 'Winning the battle'], 'He feels life is meaningless — "a walking shadow".'),
      ]),
      LS('mac-themes', 'Macbeth: themes & context', '🏰', ['Big themes: ambition, guilt, the supernatural, kingship.', 'Written for King James I, who believed in witches.'], [
        mc(1, 'Which theme is about wanting power?', 'Ambition', ['Friendship', 'Weather', 'Food'], 'Macbeth\'s "vaulting ambition" leads to his downfall.'),
        mc(1, 'Which theme links to the witches and ghosts?', 'The supernatural', ['Money', 'School', 'Love'], 'Supernatural = beyond nature: witches, ghosts, visions.'),
        mc(2, 'Which king was Shakespeare writing for?', 'King James I', ['Henry VIII', 'Queen Victoria', 'King Charles III'], 'James I was fascinated by witchcraft and wrote a book about it.'),
        mc(2, 'The "Divine Right of Kings" meant people believed…', 'Kings were chosen by God', ['Anyone could be king', 'Kings had no power', 'Witches chose kings'], 'So killing a king (regicide) was a crime against God too.'),
        mc(2, 'Blood in Macbeth mostly represents…', 'Guilt', ['Happiness', 'Wealth', 'Friendship'], 'They can\'t wash the blood — the guilt — away.'),
        mc(3, 'In 1605, just before the play, there was a plot to blow up King James. It was the…', 'Gunpowder Plot', ['Great Fire', 'Spanish Armada', 'Black Death'], 'So an audience would be horrified by a play about killing a king.'),
        mc(3, 'A good message for Shakespeare\'s audience could be…', 'Killing a king brings chaos and punishment', ['Ambition is always good', 'Witches are harmless', 'Kings should be chosen by lottery'], 'Macbeth\'s reign is chaos; order returns only with the rightful king.'),
      ]),
    ] },
    /* ---------------- ROMEO & JULIET ---------------- */
    { id: 'lRJ', book: 'rj', title: 'Romeo and Juliet', emoji: '💘', blurb: 'Two teenagers from enemy families fall in love — and it ends in tragedy.', tag: 'exam', tagText: 'Paper 1', lessons: [
      LS('rj-plot', 'R&J: the story', '📜', ['Party → love → secret wedding → Tybalt kills Mercutio → Romeo kills Tybalt → banished → fake death → both die.'], [
        mc(1, 'Where is the play set?', 'Verona, Italy', ['London', 'Scotland', 'Paris'], 'Verona — a city torn by a family feud.'),
        mc(1, 'Which two families are enemies?', 'Montagues and Capulets', ['Birlings and Crofts', 'Macbeths and Macduffs', 'Smiths and Joneses'], 'Romeo is a Montague; Juliet is a Capulet.'),
        mc(1, 'Where do Romeo and Juliet first meet?', 'At the Capulets\' party', ['In church', 'At school', 'On a ship'], 'Romeo sneaks into the Capulet party.'),
        mc(1, 'Who secretly marries them?', 'Friar Laurence', ['The Nurse', 'Prince Escalus', 'Tybalt'], 'He hopes the marriage will end the feud.'),
        od(2, 'Put these in order', ['Romeo meets Juliet at the party', 'They marry secretly', 'Tybalt kills Mercutio', 'Romeo kills Tybalt and is banished', 'Juliet takes the sleeping potion', 'Both die in the tomb'], 'Everything happens in just a few days!'),
        mc(2, 'Why is Romeo banished?', 'He kills Tybalt', ['He marries Juliet', 'He steals', 'He insults the Prince'], 'He kills Tybalt in revenge for Mercutio.'),
        mc(2, 'Who does Juliet\'s father want her to marry?', 'Paris', ['Tybalt', 'Mercutio', 'Benvolio'], 'Lord Capulet is furious when she refuses.'),
        mc(2, 'Why doesn\'t Romeo know Juliet is only asleep?', 'The Friar\'s letter never reaches him', ['He forgot', 'Juliet told him she was dead', 'He was asleep too'], 'A plague stops the letter getting to Mantua.'),
        mc(3, 'How does Juliet die?', 'She stabs herself with Romeo\'s dagger', ['She drinks poison', 'Tybalt kills her', 'She falls ill'], '"O happy dagger" — she wakes to find Romeo dead.'),
        mc(3, 'What happens after the lovers die?', 'The families make peace', ['The feud gets worse', 'The Prince is killed', 'The Nurse is banished'], 'Their deaths finally end the feud — a sad kind of hope.'),
      ]),
      LS('rj-chars', 'R&J: characters', '🎭', ['Mercutio = funny friend. Tybalt = angry cousin. Nurse = Juliet\'s carer. Friar = helper with plans.'], [
        mt(1, 'Match the character', [['Tybalt', 'Juliet\'s hot-headed cousin'], ['Mercutio', 'Romeo\'s joking friend'], ['The Nurse', 'looks after Juliet'], ['Friar Laurence', 'marries them']]),
        mc(1, 'Who is Romeo in love with at the START?', 'Rosaline', ['Juliet', 'The Nurse', 'Lady Capulet'], 'He forgets Rosaline the moment he sees Juliet — is it real love?'),
        mc(2, 'Juliet is how old?', 'Nearly 14', ['18', '21', '10'], 'Very young — which makes her courage (and the tragedy) stronger.'),
        mc(2, 'How does Lord Capulet react when Juliet refuses Paris?', 'He is furious and threatens to throw her out', ['He is proud', 'He agrees to cancel it', 'He laughs'], 'Shows how fathers controlled daughters in that time.'),
        mc(2, 'Tybalt mainly represents…', 'Hatred and violence', ['Peace', 'Love', 'Religion'], '"I hate the word, / As I hate hell, all Montagues".'),
        mc(3, 'Benvolio\'s name means "good will". He tries to…', 'Keep the peace', ['Start fights', 'Poison Romeo', 'Marry Juliet'], 'He contrasts with Tybalt.'),
        mc(3, 'How does Juliet change in the play?', 'From obedient daughter to brave, independent young woman', ['From brave to obedient', 'She doesn\'t change', 'From kind to cruel'], 'She defies her parents to stay loyal to Romeo.'),
      ]),
      LS('rj-quotes', 'R&J: key quotes', '💬', ['Learn short quotes. Who said it? What does it show?'], [
        mc(1, '"A pair of star-crossed lovers" comes from…', 'The Prologue', ['Juliet', 'Tybalt', 'The Nurse'], 'We know from the start that they are doomed by fate.'),
        mc(1, '"O Romeo, Romeo, wherefore art thou Romeo?" means…', 'Why are you Romeo (a Montague)?', ['Where are you, Romeo?', 'Hello Romeo', 'Goodbye Romeo'], '"Wherefore" means WHY — she wishes he wasn\'t from the enemy family.'),
        mc(2, '"A plague o\' both your houses!" is said by…', 'Mercutio, as he dies', ['Tybalt', 'Romeo', 'The Prince'], 'He curses both families — and the play then gets darker.'),
        mc(2, '"It is the east, and Juliet is the sun" shows Romeo thinks Juliet is…', 'Bright, beautiful and the centre of his world', ['Hot-tempered', 'Far away in the east', 'Boring'], 'A metaphor from the balcony scene.'),
        mc(2, '"My only love sprung from my only hate" — Juliet realises…', 'She loves someone from the enemy family', ['She hates love', 'Romeo is her brother', 'Tybalt is dead'], 'Love and hate are twisted together in this play.'),
        mc(3, '"These violent delights have violent ends" is said by…', 'Friar Laurence', ['Juliet', 'Capulet', 'Paris'], 'A warning that fast, intense love may end badly — foreshadowing.'),
        mc(3, '"Thus with a kiss I die" — who says it?', 'Romeo', ['Juliet', 'Paris', 'Mercutio'], 'Love and death are linked right to the end.'),
      ]),
      LS('rj-themes', 'R&J: themes & context', '⚔️', ['Big themes: love, conflict, fate, family.', 'In Elizabethan times, fathers chose who daughters married.'], [
        mc(1, 'Which theme is about the family feud?', 'Conflict', ['Weather', 'Money', 'School'], 'The feud causes violence and death.'),
        mc(1, '"Star-crossed" links to which theme?', 'Fate', ['Food', 'Money', 'Science'], 'Fate = the idea that the future is already decided (by the stars).'),
        mc(2, 'In Shakespeare\'s time, a daughter was expected to…', 'Obey her father and marry who he chose', ['Choose anyone freely', 'Never marry', 'Rule the family'], 'This is a patriarchal society — men had the power.'),
        mc(2, 'Why was honour so important to men like Tybalt?', 'Insults had to be answered, often with fighting', ['It made them rich', 'It was a type of sword', 'It was a law about marriage'], 'Honour drives the fights in Act 3.'),
        mc(3, 'Why is it a "tragedy"?', 'The main characters die because of fate and their own choices', ['It is funny', 'It has a happy ending', 'It has songs'], 'A tragedy ends in death and suffering.'),
        mc(3, 'The play is set over roughly…', 'Four or five days', ['Ten years', 'One hour', 'A whole year'], 'The speed shows how rushed and reckless everything is.'),
      ]),
    ] },
    /* ---------------- A CHRISTMAS CAROL ---------------- */
    { id: 'lACC', book: 'acc', title: 'A Christmas Carol', emoji: '👻', blurb: 'A mean old man is visited by ghosts and learns to be kind.', tag: 'exam', tagText: 'Paper 1', lessons: [
      LS('acc-plot', 'ACC: the story', '📜', ['5 staves (chapters): Marley → Past → Present → Yet to Come → Scrooge changed.'], [
        mc(1, 'What is Scrooge like at the start?', 'Mean, cold and selfish', ['Kind and generous', 'Poor and hungry', 'Young and happy'], '"Bah! Humbug!" He hates Christmas and giving money.'),
        mc(1, 'Whose ghost visits first?', 'Jacob Marley, his dead business partner', ['Tiny Tim', 'Fred', 'Belle'], 'Marley wears heavy chains — warning Scrooge to change.'),
        mc(1, 'How many spirits visit after Marley?', 'Three', ['One', 'Five', 'Ten'], 'Christmas Past, Christmas Present and Christmas Yet to Come.'),
        mc(1, 'The chapters of A Christmas Carol are called…', 'Staves', ['Acts', 'Scenes', 'Verses'], 'Like a song (a carol) — there are 5 staves.'),
        od(2, 'Put the ghosts in order', ['Marley', 'Ghost of Christmas Past', 'Ghost of Christmas Present', 'Ghost of Christmas Yet to Come'], 'Past → Present → Future.'),
        mc(2, 'Christmas Past shows Scrooge…', 'His lonely childhood and his lost love Belle', ['His own grave', 'The Cratchits\' dinner', 'A workhouse'], 'We see why he became so cold.'),
        mc(2, 'Christmas Present shows Scrooge…', 'The Cratchit family\'s happy but poor Christmas', ['His school days', 'His gravestone', 'Belle leaving him'], 'Including Tiny Tim, who is ill.'),
        mc(2, 'Christmas Yet to Come shows Scrooge…', 'His own lonely death and grave', ['His childhood', 'Fezziwig\'s party', 'Marley\'s house'], 'Nobody is sad he has died.'),
        mc(3, 'What does Scrooge do in Stave 5?', 'Buys the Cratchits a huge turkey and raises Bob\'s pay', ['Sacks Bob', 'Moves to France', 'Goes back to sleep'], 'He becomes a "second father" to Tiny Tim.'),
        mc(3, 'Who was Fezziwig?', 'Scrooge\'s kind old boss, who threw a Christmas party', ['A ghost', 'Scrooge\'s nephew', 'A beggar'], 'He shows how a good employer should treat workers — the opposite of Scrooge.'),
      ]),
      LS('acc-chars', 'ACC: characters', '🎩', ['Bob Cratchit = Scrooge\'s poor clerk. Tiny Tim = his ill son. Fred = Scrooge\'s cheerful nephew.'], [
        mt(1, 'Match the character', [['Bob Cratchit', 'Scrooge\'s clerk'], ['Tiny Tim', 'Bob\'s ill son'], ['Fred', 'Scrooge\'s nephew'], ['Belle', 'Scrooge\'s ex-fiancée']]),
        mc(1, 'Fred keeps inviting Scrooge to…', 'Christmas dinner', ['A funeral', 'Work', 'The workhouse'], 'Fred never gives up on his uncle.'),
        mc(2, 'Why did Belle end her engagement to Scrooge?', 'He loved money more than her', ['He was too poor', 'She moved away', 'He was a ghost'], 'She says a "golden" idol has replaced her.'),
        mc(2, 'Tiny Tim makes readers feel…', 'Sympathy for poor families', ['Anger at the Cratchits', 'Bored', 'Scared'], 'Dickens uses him to make us care about the poor.'),
        mc(2, 'Scrooge is described as "solitary as an…"', 'oyster', ['island', 'owl', 'orphan'], 'Hard shell outside, alone — but maybe a pearl inside?'),
        mc(3, 'The two children, Ignorance and Want, represent…', 'Problems in society caused by poverty', ['Scrooge\'s children', 'Tiny Tim\'s friends', 'Ghosts of the past'], 'A warning to rich readers to help the poor.'),
        mc(3, 'Scrooge changes because…', 'The ghosts show him the effects of his choices', ['He wins the lottery', 'Fred forces him', 'He gets ill'], 'It\'s a story of redemption — becoming a better person.'),
      ]),
      LS('acc-quotes', 'ACC: key quotes', '💬', ['Short quotes, big meaning.'], [
        mc(1, '"Bah! Humbug!" shows Scrooge thinks Christmas is…', 'Nonsense', ['Wonderful', 'Scary', 'Too short'], 'Humbug = rubbish, a fraud.'),
        mc(1, '"God bless Us, Every One!" is said by…', 'Tiny Tim', ['Scrooge', 'Marley', 'Fred'], 'His kindness contrasts with Scrooge\'s meanness.'),
        mc(2, '"Are there no prisons? … no workhouses?" — Scrooge says the poor should…', 'Go to prisons or workhouses', ['Be given money', 'Live with him', 'Get jobs at his office'], 'This shows his cruel attitude. Later the Ghost throws his words back at him.'),
        mc(2, '"I wear the chain I forged in life" — Marley means…', 'His selfish actions created his punishment', ['He likes jewellery', 'He was a blacksmith', 'He was in prison'], 'The chain is a symbol of greed and sin.'),
        mc(3, '"decrease the surplus population" — Scrooge suggests poor people should…', 'Die, to reduce the population', ['Move house', 'Have more children', 'Get better jobs'], 'A shocking view that Dickens wanted readers to reject.'),
        mc(3, '"I will honour Christmas in my heart, and try to keep it all the year" shows…', 'Scrooge has truly changed', ['He only likes December', 'He is lying', 'He is still mean'], 'His redemption is complete.'),
      ]),
      LS('acc-themes', 'ACC: themes & context', '🏚️', ['Written in 1843 — Victorian times.', 'Dickens wanted rich people to help the poor.'], [
        mc(1, 'When was A Christmas Carol published?', '1843 (Victorian times)', ['1943', '1605', '2003'], 'Queen Victoria was on the throne.'),
        mc(1, 'Which theme is about becoming a better person?', 'Redemption', ['Revenge', 'War', 'Science'], 'Scrooge is "redeemed" — saved by changing.'),
        mc(2, 'Workhouses were…', 'Harsh places where very poor people lived and worked', ['Nice hotels', 'Schools', 'Shops'], 'Families were often split up there.'),
        mc(2, 'As a boy, Dickens himself had to…', 'Work in a factory while his father was in debtors\' prison', ['Live in a palace', 'Be a ghost-hunter', 'Run a bank'], 'So he knew poverty first-hand.'),
        mc(3, 'The main message is about…', 'Social responsibility — we should look after each other', ['Getting rich', 'Ghosts being real', 'Working harder'], 'Dickens wanted readers to feel responsible for the poor.'),
        mc(3, 'Why might Dickens have used ghosts?', 'To grab readers\' attention and teach a moral lesson', ['Because they were real', 'To make it a comedy', 'To confuse readers'], 'Ghost stories were popular at Christmas — a clever way to get his message out.'),
      ]),
    ] },
    /* ---------------- JEKYLL & HYDE ---------------- */
    { id: 'lJH', book: 'jh', title: 'Jekyll and Hyde', emoji: '🧪', blurb: 'A respected doctor creates a potion that unleashes his evil side.', tag: 'exam', tagText: 'Paper 1', lessons: [
      LS('jh-plot', 'J&H: the story', '📜', ['Utterson investigates → Hyde\'s crimes → Carew murder → Lanyon\'s shock → Jekyll\'s confession.'], [
        mc(1, 'Who is the main detective-like character?', 'Mr Utterson, a lawyer', ['Dr Lanyon', 'Poole', 'Sir Danvers Carew'], 'We follow Utterson as he tries to solve the mystery.'),
        mc(1, 'What does Hyde do in the first story Enfield tells?', 'Tramples over a young girl', ['Robs a bank', 'Kills a policeman', 'Saves a child'], 'He walks right over her — a shocking, cold act.'),
        mc(1, 'Jekyll and Hyde are…', 'The same person', ['Brothers', 'Father and son', 'Enemies who never meet'], 'Jekyll\'s potion transforms him into Hyde.'),
        mc(2, 'Who does Hyde murder with a cane?', 'Sir Danvers Carew, an MP', ['Utterson', 'Lanyon', 'Poole'], 'A maid sees it from her window.'),
        mc(2, 'What happens to Dr Lanyon after seeing Hyde transform?', 'He dies of shock', ['He becomes Hyde', 'He goes to the police', 'He writes a novel'], 'Seeing it breaks his scientific beliefs.'),
        mc(2, 'Who is Poole?', 'Jekyll\'s butler', ['A policeman', 'Hyde\'s friend', 'A doctor'], 'He fetches Utterson when he fears for his master.'),
        od(3, 'Put these in order', ['Enfield\'s story about the door', 'Carew is murdered', 'Lanyon dies of shock', 'Utterson and Poole break down the door', 'Jekyll\'s confession is read'], 'The truth is only revealed at the very end, in letters.'),
        mc(3, 'Why does the story end with letters (Lanyon\'s and Jekyll\'s)?', 'The truth is revealed slowly, keeping mystery to the end', ['Stevenson ran out of time', 'Letters were cheap', 'To make it shorter'], 'The structure keeps the secret like a detective story.'),
      ]),
      LS('jh-chars', 'J&H: characters', '🎩', ['Jekyll = respectable doctor. Hyde = his evil side. Utterson = loyal lawyer.'], [
        mt(1, 'Match the character', [['Utterson', 'lawyer'], ['Lanyon', 'old doctor friend'], ['Poole', 'butler'], ['Hyde', 'violent, ape-like']]),
        mc(1, 'How is Hyde described?', 'Small, ugly and animal-like', ['Tall and handsome', 'Old and kind', 'Rich and friendly'], 'People feel disgust when they see him — "ape-like fury".'),
        mc(2, 'Why does Jekyll create Hyde?', 'To enjoy bad behaviour without ruining his reputation', ['To cure a disease', 'To become famous', 'By accident only'], 'Victorian gentlemen had to seem perfect in public.'),
        mc(2, 'Lanyon disagrees with Jekyll because…', 'Lanyon thinks Jekyll\'s science is unscientific nonsense', ['Jekyll owes him money', 'They love the same person', 'Lanyon is Hyde'], 'Rational science vs dangerous experiments.'),
        mc(3, 'By the end, Jekyll…', 'Turns into Hyde without the potion', ['Beats Hyde forever', 'Moves to Paris', 'Becomes a lawyer'], 'Hyde takes over — the evil side grows stronger.'),
        mc(3, 'Utterson values…', 'Reputation and loyalty to his friends', ['Money above everything', 'Violence', 'Gossip'], 'He tries to protect Jekyll\'s good name.'),
      ]),
      LS('jh-quotes', 'J&H: key quotes', '💬', ['Short quotes about Hyde and duality.'], [
        mc(1, '"man is not truly one, but truly two" is about…', 'Everyone having a good and bad side', ['Twins', 'Maths', 'Marriage'], 'The big idea of the book: duality.'),
        mc(2, '"If he be Mr. Hyde… I shall be Mr. Seek" shows Utterson is…', 'Determined to find Hyde', ['Scared', 'Joking about a game', 'Lying'], 'A play on words: Hide and Seek.'),
        mc(2, 'Hyde attacks Carew "with ape-like fury". This makes him seem…', 'Animal-like and uncontrolled', ['Calm', 'Clever', 'Friendly'], 'Links to Victorian fears about evolution (Darwin).'),
        mc(3, 'Hyde gives an impression of "deformity without any nameable malformation". This means…', 'He seems wrong and deformed, but no one can say exactly why', ['He has a broken leg', 'He looks normal', 'He is very tall'], 'Hyde\'s evil is hard to describe — it creates mystery and horror.'),
        mc(3, 'The fog in London often symbolises…', 'Secrecy and hidden evil', ['Happiness', 'Summer', 'Wealth'], 'Things are hidden, just like Jekyll\'s secret.'),
      ]),
      LS('jh-themes', 'J&H: themes & context', '🌫️', ['1886, Victorian London.', 'Themes: duality, reputation, science vs religion.'], [
        mc(1, 'Duality means…', 'Having two sides (good and evil)', ['Having two houses', 'A sword fight', 'A science lab'], 'Jekyll/Hyde = two sides of one man.'),
        mc(1, 'When was Jekyll and Hyde published?', '1886', ['1606', '1945', '2006'], 'Late Victorian period.'),
        mc(2, 'Victorian gentlemen cared hugely about…', 'Their reputation', ['Fashion only', 'Football', 'Social media'], 'That\'s why secrets are so important in the book.'),
        mc(2, 'Darwin\'s ideas about evolution made some Victorians fear…', 'Humans had an animal side', ['Computers', 'Ghosts', 'Winter'], 'Hyde\'s "ape-like" nature links to this fear.'),
        mc(3, 'The novella is part of which genre?', 'Gothic', ['Romantic comedy', 'Science fiction only', 'Fairy tale'], 'Gothic: darkness, mystery, horror, the supernatural.'),
        mc(3, 'A key message could be…', 'Hiding your dark side can make it more dangerous', ['Science is always good', 'Lawyers are evil', 'London is safe'], 'Jekyll\'s repression lets Hyde grow.'),
      ]),
    ] },
    /* ---------------- AN INSPECTOR CALLS ---------------- */
    { id: 'lAIC', book: 'aic', title: 'An Inspector Calls', emoji: '🕵️', blurb: 'A rich family\'s party is interrupted — and each of them helped destroy a young woman.', tag: 'exam', tagText: 'Paper 2', lessons: [
      LS('aic-plot', 'AIC: the story', '📜', ['Set in 1912, written in 1945.', 'Each Birling (and Gerald) is linked to Eva Smith\'s death.'], [
        mc(1, 'What are the Birlings celebrating at the start?', 'Sheila\'s engagement to Gerald', ['A birthday', 'Christmas', 'A new factory'], 'It all seems happy — until the doorbell rings.'),
        mc(1, 'Who arrives at the house?', 'Inspector Goole', ['A doctor', 'The Prime Minister', 'Eva Smith'], 'He says a young woman has died.'),
        mc(1, 'Who is the young woman who died?', 'Eva Smith', ['Sheila Birling', 'Edna', 'Lady Croft'], 'She also used the name Daisy Renton.'),
        mc(2, 'What did Mr Birling do to Eva?', 'Sacked her from his factory for asking for higher pay', ['Married her', 'Gave her money', 'Nothing'], 'The first link in the chain.'),
        mc(2, 'What did Sheila do?', 'Got Eva sacked from a shop out of jealousy', ['Helped her find work', 'Adopted her', 'Called the police'], 'She\'s ashamed — and changes the most.'),
        od(2, 'Order the chain of events for Eva', ['Mr Birling sacks her', 'Sheila gets her sacked from Milwards', 'Gerald has an affair with her', 'Eric gets her pregnant', 'Mrs Birling refuses her help'], 'This is the order things happened in Eva\'s life. (On stage, the Inspector questions Mrs Birling before Eric.)'),
        mc(3, 'What happens at the very end?', 'A phone call says a girl has died and an inspector is coming', ['Everyone goes to bed', 'Gerald marries Sheila', 'Eva walks in'], 'A cliffhanger — the lesson hasn\'t been learned by all.'),
        mc(3, 'What does Gerald find out about Inspector Goole?', 'There\'s no inspector of that name on the police force', ['He is Eva\'s father', 'He is Eric\'s friend', 'He is rich'], 'Was he real? Priestley leaves us wondering.'),
      ]),
      LS('aic-chars', 'AIC: characters', '🎩', ['Older Birlings refuse to change. Sheila and Eric learn their lesson.'], [
        mt(1, 'Match the character', [['Arthur Birling', 'factory owner'], ['Sybil Birling', 'charity snob'], ['Sheila', 'changes the most'], ['Eric', 'drinks too much']]),
        mc(1, 'Mr Birling calls himself…', '"a hard-headed, practical man of business"', ['"a kind father"', '"a poor worker"', '"a policeman"'], 'He only cares about money and profit.'),
        mc(2, 'Mrs Birling refused to help Eva from her…', 'Charity committee', ['Factory', 'Shop', 'School'], 'She thought Eva was being cheeky using the name "Mrs Birling".'),
        mc(2, 'Who changes the most by the end?', 'Sheila (and Eric)', ['Mr Birling', 'Mrs Birling', 'Gerald only'], 'The younger generation accepts responsibility.'),
        mc(2, 'What does the Inspector represent?', 'Priestley\'s voice — social responsibility', ['The Birlings\' butler', 'A criminal', 'The upper class'], 'He\'s like a conscience for the family and the audience.'),
        mc(3, 'Gerald is interesting because…', 'He showed Eva some kindness but still used her', ['He is completely evil', 'He is the Inspector', 'He never met Eva'], 'He\'s somewhere in the middle — and at the end he tries to wriggle out.'),
        mc(3, 'Mrs Birling blames the father of Eva\'s baby, not realising it is…', 'Eric, her own son', ['Gerald', 'Mr Birling', 'The Inspector'], 'Brilliant dramatic irony — she condemns her own son.'),
      ]),
      LS('aic-quotes', 'AIC: key quotes', '💬', ['Short quotes that show attitudes to responsibility and class.'], [
        mc(1, 'Mr Birling says the Titanic is…', '"unsinkable, absolutely unsinkable"', ['"a small boat"', '"dangerous"', '"too expensive"'], 'The audience knows it sank — dramatic irony makes Birling look foolish.'),
        mc(2, '"We are members of one body. We are responsible for each other." — said by…', 'The Inspector', ['Mr Birling', 'Gerald', 'Edna'], 'This is the heart of Priestley\'s message.'),
        mc(2, 'Mrs Birling says "girls of that class". This shows…', 'She looks down on working-class people', ['She is kind', 'She is a teacher', 'She is poor'], 'Her snobbery stops her helping Eva.'),
        mc(2, 'Sheila says "these girls aren\'t cheap labour – they\'re people". This shows…', 'She now sees working-class women as human beings', ['She wants to hire them', 'She is angry at Eva', 'She agrees with her father'], 'Sheila has changed.'),
        mc(3, 'The Inspector warns of "fire and blood and anguish". This hints at…', 'The two World Wars to come', ['A house fire', 'A cooking accident', 'A party'], 'The 1945 audience had just lived through them.'),
      ]),
      LS('aic-themes', 'AIC: themes & context', '🏭', ['Set 1912 (before WW1). Written 1945 (end of WW2).', 'Priestley was a socialist: he wanted people to care for each other.'], [
        mc(1, 'When is the play SET?', '1912', ['1945', '1850', '2012'], 'Before the First World War and the Titanic sinking.'),
        mc(1, 'When was the play WRITTEN?', '1945', ['1912', '1606', '1990'], 'Right at the end of the Second World War.'),
        mc(2, 'The main theme is…', 'Responsibility', ['Magic', 'Sport', 'Travel'], 'Who is responsible for Eva\'s death? All of them.'),
        mc(2, 'Priestley was a socialist. That means he believed…', 'Society should share wealth and look after everyone', ['Only the rich matter', 'There should be no government', 'Kings should rule'], 'The Inspector is his mouthpiece.'),
        mc(3, 'Dramatic irony is when…', 'The audience knows something the characters don\'t', ['A character tells a joke', 'The play is sad', 'Everyone is lying'], 'e.g. Birling saying there won\'t be a war.'),
        mc(3, 'Why is it clever to set the play in 1912 but show it in 1945?', 'The audience can see how wrong Birling\'s views were', ['Costumes were cheaper', 'It was a mistake', 'Priestley was born in 1912'], 'Priestley wanted 1945 audiences to build a fairer society.'),
      ]),
    ] },
    /* ---------------- POWER & CONFLICT ---------------- */
    { id: 'lPC', book: 'pc', title: 'Power and Conflict poems', emoji: '⚔️', blurb: '15 poems about power (of people and nature) and conflict (war and its effects).', tag: 'exam', tagText: 'Paper 2', lessons: [
      LS('pc-who', 'Poems & poets', '🖋️', ['Learn which poet wrote which poem — you can name them in the exam.'], [
        mt(1, 'Match the poem to its poet', [['Ozymandias', 'Shelley'], ['London', 'Blake'], ['Remains', 'Armitage'], ['Exposure', 'Owen']]),
        mt(2, 'Match the poem to its poet', [['Kamikaze', 'Garland'], ['Poppies', 'Weir'], ['Tissue', 'Dharker'], ['The Emigrée', 'Rumens']]),
        mt(2, 'Match the poem to its poet', [['My Last Duchess', 'Browning'], ['Bayonet Charge', 'Hughes'], ['Storm on the Island', 'Heaney'], ['War Photographer', 'Duffy']]),
        mt(3, 'Match the poem to its poet', [['Charge of the Light Brigade', 'Tennyson'], ['The Prelude (extract)', 'Wordsworth'], ['Checking Out Me History', 'Agard'], ['Ozymandias', 'Shelley']]),
        mc(1, 'How many poems are in the Power and Conflict cluster?', '15', ['5', '10', '20'], 'You need to know all 15, as the exam can print any of them.'),
      ]),
      LS('pc-war', 'War poems', '💣', ['Charge of the Light Brigade, Exposure, Bayonet Charge, Remains, Poppies, War Photographer, Kamikaze.'], [
        mc(1, 'Which poem is about soldiers freezing in the trenches, where "nothing happens"?', 'Exposure', ['Ozymandias', 'London', 'Tissue'], 'Wilfred Owen, WW1: the weather is the real enemy.'),
        mc(1, 'Which poem is about a mother\'s feelings as her son goes off to war?', 'Poppies', ['Remains', 'Kamikaze', 'Ozymandias'], 'Jane Weir: grief, memory and loss.'),
        mc(2, '"Someone had blundered" — which poem?', 'The Charge of the Light Brigade', ['Exposure', 'Remains', 'Bayonet Charge'], 'Tennyson: 600 soldiers ride into the "valley of Death" because of a mistaken order.'),
        mc(2, 'Which poem is about a soldier haunted by shooting a looter (PTSD)?', 'Remains', ['Poppies', 'The Emigrée', 'London'], 'Simon Armitage: "his bloody life in my bloody hands".'),
        mc(2, 'Which poem is about a pilot who turns back from a suicide mission?', 'Kamikaze', ['Bayonet Charge', 'Exposure', 'Storm on the Island'], 'Beatrice Garland: his family then treats him as if he were dead.'),
        mc(3, 'Which poem is about someone developing photos of war and noticing people back home don\'t care?', 'War Photographer', ['Tissue', 'Poppies', 'The Prelude'], 'Carol Ann Duffy: the reader\'s eyes "prick with tears" — briefly.'),
        mc(3, 'Which poem shows a soldier "suddenly" waking up in the middle of a charge?', 'Bayonet Charge', ['Exposure', 'Remains', 'Charge of the Light Brigade'], 'Ted Hughes: he runs through a field — a yellow hare appears.'),
        mc(3, 'A good pair to compare about the psychological effects of war is…', 'Remains and Kamikaze', ['London and Tissue', 'Ozymandias and The Prelude', 'Poppies and Storm on the Island'], 'Both show what happens to people after/because of the conflict.'),
      ]),
      LS('pc-power', 'Power poems', '👑', ['Human power: Ozymandias, My Last Duchess, London. Nature\'s power: Prelude, Storm on the Island.'], [
        mc(1, 'Which poem is about a broken statue of a proud king in the desert?', 'Ozymandias', ['London', 'Tissue', 'Kamikaze'], 'Shelley: human power doesn\'t last — time and nature win.'),
        mc(1, 'Which poem is a walk through a city full of suffering?', 'London', ['The Emigrée', 'Storm on the Island', 'Exposure'], 'Blake: "mind-forg\'d manacles" — people are trapped.'),
        mc(2, 'Which poem is a Duke talking about a painting of his dead wife?', 'My Last Duchess', ['Ozymandias', 'Poppies', 'Tissue'], 'Browning: controlling and jealous — "I gave commands".'),
        mc(2, 'Which poem is about a boy who steals a boat and is scared by a huge mountain?', 'The Prelude (extract)', ['Storm on the Island', 'Kamikaze', 'Remains'], 'Wordsworth: nature is more powerful than us.'),
        mc(2, 'Which poem is about islanders preparing for a violent storm?', 'Storm on the Island', ['Exposure', 'The Prelude', 'London'], 'Seamus Heaney: "We are prepared" — but are they?'),
        mc(3, 'Which poem uses paper to show that human power is fragile?', 'Tissue', ['London', 'Ozymandias', 'Remains'], 'Imtiaz Dharker: maps, receipts, the Koran — paper that can change or be torn.'),
        mc(3, 'Which poem is about being taught a history that leaves out Black heroes?', 'Checking Out Me History', ['The Emigrée', 'London', 'Tissue'], 'John Agard: identity — e.g. Toussaint L\'Ouverture and Mary Seacole.'),
        mc(3, 'Which poem remembers a childhood city through a "sunlight" memory?', 'The Emigrée', ['London', 'Poppies', 'Kamikaze'], 'Carol Rumens: the city may be at war now, but her memory stays bright.'),
        mc(3, '"Look on my works, ye Mighty, and despair!" shows the king was…', 'Arrogant — and the irony is nothing is left', ['Humble', 'Kind', 'Scared'], 'His "works" have crumbled into sand.'),
      ]),
    ] },
  ],
});
