/* ============================================================
   HOSPITALITY & CATERING — WJEC (Eduqas) Level 1/2 Vocational Award
   in Hospitality and Catering (Technical Award), QN 603/7022/1.
   Unit 1 The hospitality and catering industry — on-screen exam, 40%
     (Comberton: sat at the end of Year 10; resit possible in Year 11)
   Unit 2 Hospitality and catering in action — controlled assessment,
     60%, done in Year 11 (nutrition, menu planning, cooking, review).
   Content follows the spec sections 1.1–1.4 and 2.1–2.4.
   ============================================================ */
RC.subjects.push({
  id: 'hosp', name: 'Hospitality & Catering', emoji: '🍳',
  board: 'WJEC Level 1/2 Award in Hospitality and Catering',
  exam: 'Unit 2 controlled assessment in Year 11 (60%) · Unit 1 on-screen exam (40%): sat in Y10, resit in summer 2027 if needed',
  intro: 'Unit 2 is your big Year 11 task: nutrition, planning a menu, cooking and reviewing. Unit 1 is the industry exam (for a resit, if you need one).',
  units: [
    { id: 'o21', title: 'Unit 2 · Nutrition', emoji: '🥦', blurb: 'AC1: nutrients, who needs what, and what happens with poor nutrition.', tag: 'cw', tagText: 'Unit 2 · Y11', lessons: [
      LS('o-macro', 'Nutrients & what they do', '🥚', ['Macro-nutrients (needed in big amounts): carbohydrate, protein, fat.', 'Micro-nutrients (small amounts): vitamins and minerals.'], [
        mc(1, 'Which nutrient is the body\'s main source of ENERGY?', 'Carbohydrate', ['Vitamin C', 'Calcium', 'Water'], 'Carbs: bread, pasta, rice, potatoes.'),
        mc(1, 'Which nutrient is needed for GROWTH and REPAIR?', 'Protein', ['Carbohydrate', 'Sugar', 'Fibre'], 'Protein: meat, fish, eggs, beans, lentils.'),
        mc(1, 'Which food is high in protein?', 'Chicken', ['Apple', 'Rice', 'Butter'], 'Also fish, eggs, tofu, beans and nuts.'),
        mt(1, 'Match the nutrient to its job', [['Carbohydrate', 'energy'], ['Protein', 'growth & repair'], ['Fat', 'warmth & energy store'], ['Fibre', 'healthy digestion']]),
        mc(2, 'Calcium is needed for…', 'Strong bones and teeth', ['Energy', 'Healthy eyesight', 'Healing cuts only'], 'Calcium: milk, cheese, yoghurt. Works with vitamin D.'),
        mc(2, 'Iron is needed for…', 'Healthy red blood cells', ['Strong nails only', 'Digestion', 'Energy storage'], 'Too little iron → anaemia (tiredness). Found in red meat, spinach.'),
        mc(2, 'Vitamin C helps…', 'The immune system and absorbing iron', ['Bones only', 'Store fat', 'Nothing'], 'Found in citrus fruit, peppers, berries.'),
        mc(2, 'Which vitamins are FAT-soluble?', 'A and D', ['B and C', 'C only', 'All of them'], 'A & D dissolve in fat. B group & C dissolve in water.'),
        mc(3, 'Vitamin D helps the body to…', 'Absorb calcium', ['Digest fibre', 'Make sugar', 'See in colour'], 'We make it from sunlight too.'),
        mc(3, 'Too much sodium (salt) can cause…', 'High blood pressure', ['Stronger bones', 'Better eyesight', 'Anaemia'], 'Adults should have less than 6 g of salt a day.'),
        mc(3, 'Dietary fibre (NSP) helps prevent…', 'Constipation', ['Anaemia', 'Rickets', 'Scurvy'], 'Fibre: wholemeal bread, fruit, veg, beans.'),
      ]),
      LS('o-needs', 'Who needs what?', '👵', ['Different life stages and diets need different foods.', 'Vegans eat NO animal products. Vegetarians eat no meat or fish.'], [
        mc(1, 'A vegetarian does NOT eat…', 'Meat or fish', ['Vegetables', 'Eggs and cheese', 'Bread'], 'Some vegetarians eat eggs and dairy.'),
        mc(1, 'A vegan does NOT eat…', 'Any animal products (meat, fish, eggs, dairy, honey)', ['Vegetables', 'Fruit', 'Beans'], 'Vegans get protein from beans, lentils, tofu, nuts.'),
        mc(1, 'A pescatarian eats fish but not…', 'Meat', ['Vegetables', 'Bread', 'Fruit'], 'Pesca = fish.'),
        mc(2, 'Someone with coeliac disease must avoid…', 'Gluten (wheat, barley, rye)', ['Sugar', 'Vegetables', 'Rice'], 'Gluten damages their gut.'),
        mc(2, 'Someone who is lactose intolerant can\'t digest…', 'The sugar in milk', ['Meat', 'Bread', 'Fruit'], 'They can choose lactose-free milk or plant milks.'),
        mc(2, 'Teenagers need extra…', 'Calcium and iron (growing bones, periods)', ['Salt', 'Sugar', 'Alcohol'], 'Growth spurts need lots of nutrients.'),
        mc(2, 'Elderly people often need more…', 'Calcium and vitamin D (for bones), and fibre', ['Salt', 'Sugar', 'Fat'], 'Bones get weaker with age.'),
        mc(3, 'Someone with Type 2 diabetes should…', 'Limit sugar and choose slow-release carbs', ['Eat lots of sweets', 'Avoid all vegetables', 'Drink more fizzy drinks'], 'Wholegrains, fibre and fewer sugary foods.'),
        mc(3, 'A Muslim customer may not eat…', 'Pork, and meat that isn\'t halal', ['Vegetables', 'Rice', 'Fish'], 'Religious dietary needs are part of menu planning.'),
        mc(3, 'A Hindu customer often avoids…', 'Beef', ['Rice', 'Vegetables', 'Milk'], 'Many Hindus are vegetarian; cows are sacred.'),
        mc(3, 'Someone with heart disease (cardiovascular) should reduce…', 'Saturated fat and salt', ['Fruit', 'Fibre', 'Water'], 'Too much saturated fat raises cholesterol.'),
      ]),
      LS('o-poor', 'Poor nutrition & cooking methods', '🍟', ['Too little OR too much of a nutrient both cause problems.', 'Boiling veg loses vitamin C into the water. Steaming keeps more.'], [
        mc(1, 'Eating too much sugar can cause…', 'Tooth decay and weight gain', ['Strong bones', 'Better eyesight', 'Anaemia'], 'Also Type 2 diabetes.'),
        mc(1, 'Not enough iron can cause…', 'Anaemia (feeling tired and weak)', ['Rickets', 'Obesity', 'Tooth decay'], 'Iron carries oxygen in the blood.'),
        mc(2, 'Not enough calcium or vitamin D can cause…', 'Weak bones (rickets in children)', ['Anaemia', 'Scurvy', 'Obesity'], 'Rickets = soft, weak bones.'),
        mc(2, 'Not enough vitamin C can cause…', 'Scurvy', ['Rickets', 'Anaemia', 'Diabetes'], 'Scurvy: bleeding gums, slow healing.'),
        mc(2, 'Which cooking method ADDS the most fat?', 'Deep frying', ['Steaming', 'Grilling', 'Poaching'], 'The food soaks up oil.'),
        mc(2, 'Why is grilling healthier than frying?', 'Fat drips away from the food', ['It adds oil', 'It adds sugar', 'It keeps all the fat in'], 'Grilling reduces fat.'),
        mc(3, 'Why does boiling vegetables lose nutrients?', 'Water-soluble vitamins (B and C) leak into the water', ['The heat adds fat', 'It removes protein', 'It adds salt'], 'Use little water, cook briefly, or steam instead.'),
        mc(3, 'Which method keeps the most vitamin C in broccoli?', 'Steaming', ['Boiling for 20 minutes', 'Deep frying', 'Roasting in oil'], 'Steaming doesn\'t soak the veg in water.'),
        mc(3, 'Stir-frying is quite healthy because…', 'It is quick and uses a little oil', ['It uses lots of oil', 'It takes hours', 'It boils the food'], 'Short cooking time keeps more vitamins.'),
      ]),
    ] },
    { id: 'o22', title: 'Unit 2 · Menus & cooking', emoji: '📋', blurb: 'AC2 & AC3: planning dishes, a time plan, skills and presentation — then reviewing.', tag: 'cw', tagText: 'Unit 2 · Y11', lessons: [
      LS('o-menu', 'Planning a menu', '🗒️', ['Think: cost, customers, equipment, skills, time, season, the environment.'], [
        mc(1, 'When planning a menu for a children\'s party, you mostly think about…', 'The customers (children\'s tastes and needs)', ['Wine prices', 'Michelin stars', 'Hotel rooms'], 'Always match the menu to the customer.'),
        mc(1, 'Using foods when they are naturally grown in that season is called…', 'Seasonality', ['Portion control', 'Mise en place', 'Garnishing'], 'Seasonal food is cheaper, fresher and better for the environment.'),
        mc(1, 'Portion control means…', 'Serving the right amount each time', ['Cooking faster', 'Using leftovers', 'Adding garnish'], 'Controls cost and keeps customers happy.'),
        mc(2, '"Organoleptic" qualities are…', 'How food looks, smells, tastes, feels and sounds', ['How much it costs', 'Where it comes from', 'How long it lasts'], 'The senses! Important when choosing and reviewing dishes.'),
        mc(2, 'Reduce, reuse, recycle helps with…', 'Sustainability (environmental issues)', ['Speed', 'Presentation', 'Nutrition'], 'e.g. saving water and energy, less waste.'),
        mc(2, 'A way to save energy in the kitchen is…', 'Using lids on pans and filling the oven', ['Leaving the oven on all day', 'Boiling a full kettle for one cup', 'Using the biggest pan'], 'Conserving energy is part of the environmental factor.'),
        mc(3, 'Why must you check the equipment available before choosing a dish?', 'You can\'t make a dish without the right tools', ['It is the law', 'Equipment is always the same', 'It makes food cheaper'], 'e.g. no pasta machine → choose a different dish.'),
        mc(3, 'Why should dishes show a range of skills?', 'Complex skills earn more marks and show your ability', ['Simple dishes are banned', 'It saves time', 'Customers don\'t care'], 'The spec rates techniques as basic, medium or complex.'),
      ]),
      LS('o-plan', 'Time plans & kitchen words', '⏱️', ['Mise en place = everything ready before you cook.', 'Dovetailing = doing two dishes at once, fitting tasks together.'], [
        mc(1, '"Mise en place" means…', 'Getting everything ready before cooking', ['Washing up', 'Serving the food', 'A French dessert'], 'French for "everything in its place".'),
        mc(1, 'A "contingency" in a time plan is…', 'What you\'ll do if something goes wrong', ['The main ingredient', 'The serving time', 'A type of knife'], 'e.g. "If the sauce is lumpy, sieve it."'),
        mc(2, '"Dovetailing" means…', 'Fitting the steps of two dishes together to save time', ['Cooking a bird', 'Decorating a cake', 'Chilling food'], 'e.g. prepare the salad while the chicken roasts.'),
        mc(2, 'A "quality point" is…', 'A check to make sure the dish is good (e.g. golden brown)', ['The price of a dish', 'A menu section', 'A hygiene rule'], 'Quality points show you\'re checking your work.'),
        mc(2, 'Hot food on hold for serving must stay above…', '63°C', ['5°C', '37°C', '100°C'], 'Hot holding = 63°C or above.'),
        od(2, 'Order the time plan stages', ['Mise en place', 'Cooking', 'Cooling / hot holding', 'Serving'], 'Your time plan should include health and safety at each step.'),
        mc(3, 'A good time plan includes…', 'Timings, equipment, hygiene points and contingencies', ['Only the recipe title', 'Just the shopping list', 'Only the cost'], 'Commodity list + timing + safety + quality + contingencies.'),
        mc(3, 'Why cool food quickly before putting it in the fridge?', 'To stop bacteria growing in the danger zone', ['To save money', 'To make it taste nicer', 'It doesn\'t matter'], 'Cool within 90 minutes, then refrigerate.'),
      ]),
      LS('o-skills', 'Skills & presentation', '🔪', ['Knife skills: julienne = thin matchsticks, brunoise = tiny cubes.', 'Presentation: garnish, portion control, accompaniments.'], [
        mc(1, 'Which of these is a knife skill?', 'Dicing', ['Whisking', 'Kneading', 'Baking'], 'Dicing = cutting into cubes.'),
        mc(1, 'Garnishing means…', 'Decorating a dish to make it look good', ['Washing the dish', 'Weighing the food', 'Freezing it'], 'e.g. a sprig of parsley or a lemon twist.'),
        mt(2, 'Match the cut', [['Julienne', 'thin matchsticks'], ['Brunoise', 'tiny cubes'], ['Chiffonade', 'thin ribbons of leaves'], ['Batons', 'thick sticks']]),
        mc(2, 'Making bread dough stretchy by pushing and folding is…', 'Kneading', ['Creaming', 'Whisking', 'Rubbing in'], 'A medium skill in the spec.'),
        mc(2, 'Which of these is rated a COMPLEX skill?', 'Piping', ['Grating', 'Peeling', 'Mashing'], 'Complex skills include piping, filleting, laminating pastry and brunoise.'),
        mc(2, 'An "accompaniment" is…', 'Something served alongside the main dish', ['The chef\'s helper', 'A knife', 'A cooking method'], 'e.g. a side salad or a sauce.'),
        mc(3, 'Baking a pastry case before adding the filling is called…', 'Baking blind', ['Blanching', 'Braising', 'Basting'], 'Stops a soggy bottom!'),
        mc(3, 'Briefly boiling veg, then plunging it in iced water is…', 'Blanching', ['Poaching', 'Braising', 'Deglazing'], 'Keeps the colour bright.'),
        mc(3, 'Removing the bones from a fish is…', 'Filleting', ['Spatchcocking', 'Tenderising', 'Zesting'], 'A complex skill.'),
      ]),
      LS('o-review', 'Reviewing your work', '🔁', ['Review the DISH (taste, look, safety, waste)', 'and YOURSELF (planning, time, decisions).'], [
        mc(1, 'When you review a dish, you think about…', 'Taste, presentation, hygiene and what you\'d improve', ['Only the price', 'Only who ate it', 'Nothing'], 'Strengths AND improvements.'),
        mc(2, 'Which is a good review sentence?', 'My sauce was smooth and glossy, but next time I\'d add less salt.', ['It was nice.', 'I cooked food.', 'It was bad.'], 'Specific + a strength + an improvement.'),
        mc(2, 'Reviewing your own performance includes…', 'Time management, organisation and decision making', ['Your favourite colour', 'What others wore', 'The weather'], 'Spec 2.4.2: strengths and weaknesses in your planning and timing.'),
        mc(3, 'Why mention waste in a review?', 'Less waste saves money and is better for the environment', ['Waste improves taste', 'It is not important', 'Examiners love bins'], 'Links back to sustainability.'),
        mc(3, 'The best way to describe taste in a review is…', 'Using organoleptic words like "tangy", "crisp", "creamy"', ['Saying "yum"', 'Giving a score only', 'Not mentioning it'], 'Sensory vocabulary shows detail.'),
      ]),
    ] },
    { id: 'o11', title: 'Unit 1 · The industry', emoji: '🏨', blurb: 'Providers, jobs, contracts, costs and customers (for a Unit 1 resit).', tag: 'exam', tagText: 'Unit 1 exam', lessons: [
      LS('o-prov', 'Hospitality providers', '🏨', ['Commercial = makes a profit (hotels, cafés).', 'Non-commercial = not for profit (hospitals, schools, prisons).'], [
        mc(1, 'A hotel is a…', 'Commercial residential provider', ['Non-commercial provider', 'Charity', 'Hospital'], 'Commercial = for profit. Residential = you can stay overnight.'),
        mc(1, 'A school canteen is…', 'Non-commercial', ['Commercial residential', 'A restaurant chain', 'A cruise ship'], 'Non-commercial = not mainly for profit.'),
        mc(1, 'A fast-food takeaway is…', 'Commercial non-residential', ['Non-commercial residential', 'A care home', 'A prison'], 'For profit, but you don\'t stay overnight.'),
        mc(2, 'Which is non-commercial RESIDENTIAL?', 'A hospital or care home', ['A café', 'A hotel', 'A food truck'], 'People stay, and it isn\'t run for profit.'),
        mc(2, 'Silver service is a type of…', 'Table service', ['Counter service', 'Vending', 'Takeaway'], 'Waiters serve food from a platter at the table.'),
        mc(2, 'A buffet is a type of…', 'Counter / self-service', ['Table service', 'Room service', 'Silver service'], 'Customers help themselves.'),
        mc(3, 'A Michelin star is awarded to…', 'Excellent restaurants', ['Hotels with pools', 'Fast-food outlets', 'Schools'], 'Also: AA Rosettes, the Good Food Guide. Hotels get star ratings.'),
        mc(3, 'Meals on Wheels is…', 'A non-commercial service delivering meals to people at home', ['A fast-food chain', 'A food truck festival', 'A cruise ship'], 'Often for elderly people.'),
      ]),
      LS('o-jobs', 'Jobs & working conditions', '👩‍🍳', ['Kitchen brigade: executive chef → sous chef → chef de partie → commis chef.', 'Front of house = customer-facing. Back of house = kitchen, stores.'], [
        mc(1, 'The head chef in charge of the kitchen is the…', 'Executive chef', ['Commis chef', 'Kitchen porter', 'Concierge'], 'At the top of the kitchen brigade.'),
        mc(1, 'A waiter works…', 'Front of house', ['Back of house', 'In the stores', 'In the laundry'], 'Front of house = where customers are.'),
        od(2, 'Order the kitchen brigade from the top', ['Executive chef', 'Sous chef', 'Chef de partie', 'Commis chef'], 'Sous = "under" — second in charge. Commis = junior chef.'),
        mc(2, 'The kitchen porter (plongeur) mainly…', 'Washes up and cleans', ['Cooks the main dishes', 'Greets guests', 'Runs the hotel'], 'An essential back-of-house job.'),
        mc(2, 'A zero-hours contract means…', 'No guaranteed hours each week', ['Always 40 hours', 'No pay at all', 'Only night shifts'], 'Flexible, but income can be unpredictable.'),
        mc(2, 'Seasonal work is…', 'Work only at busy times of year (e.g. summer)', ['Always full-time', 'Weekend only', 'Unpaid'], 'Hospitality is busier in holidays.'),
        mc(3, 'A salary is…', 'A fixed yearly amount, paid monthly', ['Paid per hour', 'Tips only', 'A bonus'], 'A wage is usually paid per hour.'),
        mc(3, 'Which personal quality matters most for a receptionist?', 'Good communication and a friendly manner', ['Being able to fillet fish', 'Working alone quietly', 'Knowing butchery'], 'Front-of-house staff deal with customers all day.'),
      ]),
      LS('o-money', 'Costs, profit & customers', '💷', ['Costs: labour (staff), materials (food), overheads (bills, rent).', 'Gross profit = sales − food cost. Net profit = gross profit − all other costs.'], [
        mc(1, 'Staff wages are which type of cost?', 'Labour', ['Materials', 'Overheads', 'Profit'], 'Labour = paying people.'),
        mc(1, 'Electricity, rent and insurance are…', 'Overheads', ['Materials', 'Labour', 'Profit'], 'Running costs of the building.'),
        mc(2, 'A café takes £500 and the food cost £200. Gross profit is…', '£300', ['£700', '£200', '£500'], 'Gross profit = sales − cost of food = 500 − 200.'),
        mc(2, 'Net profit is…', 'Gross profit minus all other costs (labour, overheads)', ['The same as sales', 'Money before food costs', 'Only tips'], 'Net = what\'s truly left over.'),
        mc(2, 'Online booking and card-key rooms are examples of…', 'New technology', ['Overheads', 'Seasonality', 'Portion control'], 'Technology can speed things up and improve service.'),
        mc(3, 'Bad reviews on social media can…', 'Lose a business customers', ['Always help it', 'Change the VAT rate', 'Have no effect'], 'Media can have positive and negative effects.'),
        mc(3, 'When the economy is weak, restaurants often…', 'Have fewer customers', ['Get busier', 'Raise all prices easily', 'Close for good immediately'], 'People eat out less when money is tight.'),
        mc(3, 'Making buildings accessible to wheelchair users meets…', 'Customer rights and inclusion (equality)', ['Seasonality', 'Portion control', 'Food safety'], 'Providers must meet the needs of all customers.'),
      ]),
    ] },
    { id: 'o13', title: 'Unit 1 · Safety & food poisoning', emoji: '🦠', blurb: 'Health & safety laws, HACCP, bacteria, allergies and the EHO. Also needed for Unit 2 practicals!', tag: 'exam', tagText: 'Unit 1 exam', lessons: [
      LS('o-temps', 'Food safety temperatures', '🌡️', ['Fridge: 0–5°C.  Freezer: −18°C or below.', 'Cook to 75°C in the centre.  Hot hold above 63°C.  Danger zone: 5–63°C.'], [
        mc(1, 'A fridge should be between…', '0°C and 5°C', ['10°C and 20°C', '−18°C and −25°C', '63°C and 75°C'], 'Cold slows bacteria down.'),
        mc(1, 'A freezer should be at…', '−18°C or colder', ['0°C', '5°C', '10°C'], 'Freezing stops bacteria growing (but doesn\'t kill them).'),
        mc(1, 'The "danger zone" where bacteria grow fastest is…', '5°C to 63°C', ['0°C to 5°C', '75°C to 100°C', '−18°C to 0°C'], 'Keep food out of this zone as much as possible.'),
        mc(2, 'Food should be cooked until the centre (core) reaches…', '75°C', ['37°C', '50°C', '5°C'], 'Check with a clean food probe.'),
        mc(2, 'Hot food on display must be kept above…', '63°C', ['37°C', '5°C', '0°C'], 'Hot holding.'),
        mc(2, 'The best way to defrost chicken is…', 'In the fridge, on the bottom shelf', ['On the kitchen counter', 'In warm water', 'In the sun'], 'Stays out of the danger zone; bottom shelf stops drips.'),
        mc(3, 'Bacteria grow fastest at around…', '37°C (body temperature)', ['0°C', '75°C', '−18°C'], 'That\'s why the danger zone matters.'),
        mc(3, 'Why is raw meat stored on the BOTTOM shelf of the fridge?', 'So blood can\'t drip onto ready-to-eat food', ['It is heavier', 'It stays warmer', 'It looks better'], 'Prevents cross-contamination.'),
      ]),
      LS('o-bugs', 'Food poisoning & allergies', '🤢', ['Food poisoning bacteria: salmonella, E. coli, listeria, campylobacter, staphylococcus aureus, bacillus cereus, clostridium perfringens.'], [
        mc(1, 'Salmonella is often found in…', 'Raw chicken and eggs', ['Bread', 'Apples', 'Rice cakes'], 'Cook thoroughly to kill it.'),
        mc(1, 'Common symptoms of food poisoning are…', 'Vomiting, diarrhoea and stomach ache', ['Sneezing', 'A broken arm', 'Better sleep'], 'Visible: vomiting, diarrhoea. Non-visible: feeling sick, stomach ache.'),
        mc(2, 'Bacillus cereus is linked to…', 'Cooked rice left out too long', ['Raw fish only', 'Tap water', 'Fresh fruit'], 'Cool rice quickly and don\'t reheat more than once.'),
        mc(2, 'Listeria can grow even in the fridge and is found in…', 'Soft cheese and pâté', ['Crisps', 'Dry pasta', 'Sugar'], 'Pregnant women are advised to avoid these.'),
        mc(2, 'Staphylococcus aureus often spreads from…', 'People\'s hands, noses and cuts', ['Cold water', 'Frozen peas', 'Salt'], 'Good personal hygiene stops it.'),
        mc(2, 'A food ALLERGY can cause…', 'Anaphylactic shock (swelling, can\'t breathe)', ['Mild hunger', 'Sleepiness only', 'Nothing'], 'Can be life-threatening — an EpiPen may be needed.'),
        mc(2, 'A food INTOLERANCE (like lactose) usually causes…', 'Bloating and stomach pain', ['Anaphylaxis', 'Broken bones', 'Rashes only'], 'Uncomfortable, but not usually life-threatening.'),
        mc(3, 'Which of these is one of the main allergens that must be labelled?', 'Peanuts', ['Potatoes', 'Rice', 'Carrots'], 'Others include: gluten cereals, milk, eggs, fish, crustaceans, molluscs, sesame, soya, lupin, nuts…'),
        mc(3, 'Cross-contamination is…', 'Bacteria spreading from raw food to ready-to-eat food', ['Mixing two sauces', 'Cooking at two temperatures', 'Serving two courses'], 'Prevent it with coloured boards, handwashing and fridge order.'),
        mt(3, 'Match the chopping board colour', [['Red', 'raw meat'], ['Blue', 'raw fish'], ['Green', 'salad & fruit'], ['Yellow', 'cooked meat']]),
      ]),
      LS('o-laws', 'Health & safety laws', '⚖️', ['HASAWA 1974, COSHH 2002, RIDDOR 2013, Manual Handling 1992, PPER 1992.', 'HACCP = spotting hazards and controlling them.'], [
        mc(1, 'PPE stands for…', 'Personal Protective Equipment', ['Private Party Event', 'Public Pay Entry', 'Personal Pan Equipment'], 'e.g. aprons, oven gloves, hats.'),
        mc(1, 'COSHH is about…', 'Safe use and storage of hazardous chemicals', ['Lifting heavy boxes', 'Reporting accidents', 'Cooking temperatures'], 'Control of Substances Hazardous to Health (2002) — e.g. cleaning chemicals.'),
        mc(2, 'RIDDOR requires employers to…', 'Report serious injuries, diseases and dangerous events', ['Wear aprons', 'Label allergens', 'Cook to 75°C'], 'Reporting of Injuries, Diseases and Dangerous Occurrences Regulations (2013).'),
        mc(2, 'The Manual Handling Regulations are about…', 'Lifting and carrying safely', ['Handwashing', 'Menus', 'Chemicals'], 'Bend your knees, keep your back straight.'),
        mt(2, 'Match the law', [['HASAWA 1974', 'overall safety at work'], ['COSHH', 'chemicals'], ['RIDDOR', 'report injuries'], ['PPER', 'protective clothing']]),
        mc(2, 'HACCP stands for…', 'Hazard Analysis and Critical Control Points', ['Hot And Cold Cooking Points', 'Health And Care Catering Plan', 'Hygiene And Clean Cooking Practice'], 'Find each hazard, control it, and keep records.'),
        mc(3, 'In HACCP, a "critical control point" is…', 'A step where you can stop a hazard (e.g. cooking to 75°C)', ['The till', 'The chef\'s office', 'The menu'], 'Measure it, record it, act if it goes wrong.'),
        mc(3, 'Who is responsible for staff health and safety training?', 'The employer', ['The customers', 'The EHO', 'Nobody'], 'Employees must also follow the rules and use PPE.'),
        mc(3, 'An EHO (Environmental Health Officer) can…', 'Inspect businesses and close them if unsafe', ['Cook the food', 'Hire the staff', 'Write the menu'], 'They also investigate food poisoning outbreaks and give evidence in court.'),
      ]),
    ] },
  ],
});
