/* ============================================================
   HEALTH & SOCIAL CARE — Pearson BTEC Level 1/Level 2 Tech Award
   (2022 spec). Comberton's curriculum map:
     Y10: Component 1 Human Lifespan Development (internal, 30%)
          Component 2 Health & Social Care Services & Values (internal, 30%)
     Y11: Component 3 Health & Wellbeing — EXTERNAL EXAM, May (40%)
   Component 3 is a 2-hour, 60-mark synoptic exam, so it comes first,
   and it draws on what she learned in Components 1 and 2.
   ============================================================ */
RC.subjects.push({
  id: 'hsc', name: 'Health & Social Care', emoji: '🩺',
  board: 'Pearson BTEC Tech Award in Health and Social Care',
  exam: 'Component 3 exam: 2 hours, 60 marks, May 2027 (40% of the grade). Components 1 & 2 are coursework.',
  intro: 'The exam (Component 3) is about ONE person\'s health: what affects it, how to measure it, and a plan to improve it.',
  units: [
    { id: 'hC3a', title: 'C3 · What affects health', emoji: '🍎', blurb: 'Factors that make health and wellbeing better or worse.', tag: 'exam', tagText: 'EXAM · May', lessons: [
      LS('h-def', 'What is health?', '💚', ['Holistic = the WHOLE person.', 'PIES: Physical, Intellectual, Emotional, Social.'], [
        mc(1, 'What does PIES stand for?', 'Physical, Intellectual, Emotional, Social', ['Pain, Illness, Exercise, Sleep', 'Physical, Internal, Eating, Sport', 'People, Ideas, Energy, Safety'], 'PIES covers every side of a person.'),
        mc(1, 'A "holistic" view of health looks at…', 'The whole person — body, mind and social life', ['Only illness', 'Only fitness', 'Only money'], 'Holistic = whole. Not just "not being ill".'),
        mc(1, 'Feeling happy and confident is part of…', 'Emotional wellbeing', ['Physical health', 'Intellectual health', 'Economic health'], 'Emotions = feelings, self-esteem, confidence.'),
        mt(1, 'Match the PIES area', [['Physical', 'body'], ['Intellectual', 'thinking'], ['Emotional', 'feelings'], ['Social', 'relationships']]),
        mc(2, 'Learning new skills and solving problems is…', 'Intellectual', ['Physical', 'Social', 'Emotional'], 'Intellectual = the brain: thinking, memory, learning.'),
        tf(2, 'Health just means not having an illness.', false, 'A holistic definition includes physical, mental and social wellbeing — not only the absence of disease.'),
        mc(3, 'A "positive" definition of health means…', 'Having good physical, mental and social wellbeing', ['Having no illness at all', 'Being very rich', 'Never going to the doctor'], 'The World Health Organization defines health as complete physical, mental and social wellbeing.'),
        mc(3, 'Someone lonely after moving house may have poor…', 'Social and emotional wellbeing', ['Only physical health', 'Only intellectual health', 'Economic health'], 'Isolation affects relationships (social) and feelings (emotional).'),
      ]),
      LS('h-factors', 'Factors: body & lifestyle', '🚬', ['Physical factors: genes, illness, diet, exercise.', 'Lifestyle: smoking, alcohol, drugs, hygiene.'], [
        mc(1, 'Which is a LIFESTYLE factor?', 'Smoking', ['Genetic inheritance', 'Age', 'Height'], 'Lifestyle = choices we make, like smoking, drinking or exercise.'),
        mc(1, 'A condition passed from parents to children is…', 'Genetic inheritance', ['A lifestyle choice', 'An economic factor', 'A life event'], 'e.g. cystic fibrosis is inherited.'),
        mc(1, 'Which helps physical health?', 'Regular exercise', ['Smoking', 'Sitting all day', 'Skipping meals'], 'Exercise strengthens the heart and muscles and helps weight.'),
        mc(2, 'Drinking too much alcohol can cause…', 'Liver damage', ['Stronger bones', 'Better sleep', 'Taller growth'], 'Also high blood pressure, heart disease, some cancers.'),
        mc(2, 'An "acute" illness is…', 'Short-term (e.g. flu)', ['Long-term (e.g. diabetes)', 'Always serious', 'Not an illness'], 'Acute = sudden and short. Chronic = long-lasting.'),
        mc(2, 'A "chronic" illness is…', 'Long-lasting, like asthma or diabetes', ['Over in a day', 'Always caught from others', 'Only in children'], 'Chronic conditions can affect every part of PIES.'),
        mc(2, 'Poor personal hygiene can lead to…', 'Infections and being socially isolated', ['Better friendships', 'More energy', 'Weight gain only'], 'It affects physical AND social wellbeing.'),
        mc(3, 'How might a poor diet affect EMOTIONAL wellbeing?', 'Weight gain could lower self-esteem', ['It improves confidence', 'No effect at all', 'It makes you taller'], 'Always link the factor to a PIES area — that\'s what the exam wants.'),
        mc(3, 'Substance misuse (drugs) can affect intellectual health by…', 'Harming memory and concentration', ['Improving grades', 'Building muscle', 'Helping sleep'], 'Explain effects across PIES for full marks.'),
      ]),
      LS('h-factors2', 'Factors: people, money, home', '🏠', ['Social: friends, family, isolation.  Economic: money, job.', 'Environmental: housing, pollution.  Life events: big changes.'], [
        mc(1, 'Which is an ECONOMIC factor?', 'Income (how much money you have)', ['Friendships', 'Pollution', 'Genes'], 'Economic = money: income, savings, job.'),
        mc(1, 'Which is an ENVIRONMENTAL factor?', 'Damp, cold housing', ['Your income', 'Smoking', 'Friendships'], 'Environment = where you live: housing, pollution, noise.'),
        mc(1, 'Having supportive friends and family is good for…', 'Social and emotional wellbeing', ['Only physical health', 'Economic health', 'Nothing'], 'Support = someone to talk to, lower stress.'),
        mc(2, 'Social isolation means…', 'Being cut off from other people', ['Having lots of friends', 'Living in a city', 'Being ill'], 'Isolation can cause loneliness, depression and low self-esteem.'),
        mc(2, 'Damp housing can cause…', 'Breathing problems like asthma', ['Better sleep', 'Stronger bones', 'Weight loss'], 'Mould and damp harm the lungs.'),
        mc(2, 'Being unemployed can affect health because…', 'Less money for healthy food and more stress', ['It always improves fitness', 'It has no effect', 'It gives more money'], 'Economic factors affect diet, housing and stress.'),
        mc(2, 'Culture and religion can affect health by…', 'Influencing diet and whether people seek help', ['Changing height', 'Changing genes', 'Having no effect'], 'e.g. some people may prefer a doctor of the same gender.'),
        mc(3, 'Which is a "relationship change" life event?', 'Divorce', ['Losing a job', 'Breaking a leg', 'Moving house'], 'Relationship changes: marriage, divorce, bereavement, becoming a parent.'),
        mc(3, 'Which is a "change in life circumstances"?', 'Redundancy (losing your job)', ['Getting married', 'Catching flu', 'Having a baby'], 'Life circumstances: moving house, redundancy, retirement, imprisonment.'),
        mc(3, 'Someone\'s partner dies (bereavement). A likely EMOTIONAL effect is…', 'Grief and low mood', ['Better fitness', 'More money', 'Taller'], 'Life events can affect all of PIES.'),
      ]),
    ] },
    { id: 'hC3b', title: 'C3 · Measuring health', emoji: '📏', blurb: 'The numbers in the exam: pulse, blood pressure, peak flow, BMI.', tag: 'exam', tagText: 'EXAM · May', lessons: [
      LS('h-phys', 'Body measurements', '❤️', ['Resting pulse (adults): 60–100 beats per minute.', 'Healthy blood pressure: about 90/60 to 120/80.'], [
        mc(1, 'What does pulse (heart rate) measure?', 'How many times the heart beats in a minute', ['How tall you are', 'How much you weigh', 'How much air you breathe'], 'Measured in beats per minute (bpm).'),
        mc(1, 'A normal resting heart rate for an adult is…', '60–100 bpm', ['10–20 bpm', '150–200 bpm', '0–10 bpm'], 'Fitter people often have a lower resting rate.'),
        mc(1, 'Which measurement tells you about the LUNGS?', 'Peak flow', ['BMI', 'Pulse', 'Blood pressure'], 'Peak flow = how fast you can blow air out.'),
        mc(2, 'Blood pressure is written like 120/80. The top number is…', 'Systolic (when the heart beats)', ['Diastolic (when the heart rests)', 'Your pulse', 'Your age'], 'Top = systolic, bottom = diastolic. Measured in mmHg.'),
        mc(2, 'A blood pressure of 150/95 is…', 'High', ['Healthy', 'Low', 'Perfect'], '140/90 or above is considered high.'),
        mc(2, 'High blood pressure increases the risk of…', 'Heart attack and stroke', ['Colds', 'Broken bones', 'Short-sightedness'], 'It puts strain on the heart and blood vessels.'),
        mc(2, 'A low peak flow reading could suggest…', 'Asthma or narrowed airways', ['Being very fit', 'High blood pressure', 'Being tall'], 'Peak flow depends on age, height and sex — compare to their expected value.'),
        mc(3, 'After exercise, a fit person\'s pulse will…', 'Return to resting quickly', ['Stay high for hours', 'Stop', 'Never change'], 'A quick recovery rate = a healthy heart.'),
        mc(3, 'Someone\'s blood pressure is 85/55. This is…', 'Low', ['Healthy', 'High', 'Very high'], 'Below 90/60 is low — can cause dizziness and fainting.'),
        mc(3, 'Why do we compare readings to "published guidance"?', 'To see if a result is healthy or a risk', ['To make it longer', 'Because it\'s the law', 'To guess their age'], 'In the exam you interpret the number, then explain the risk.'),
      ]),
      LS('h-bmi', 'BMI', '⚖️', ['BMI = weight (kg) ÷ height (m) ÷ height (m).', 'Healthy BMI: 18.5 to 24.9.'], [
        mc(1, 'BMI stands for…', 'Body Mass Index', ['Blood Measure Indicator', 'Big Muscle Index', 'Body Muscle Intake'], 'It compares weight to height.'),
        mc(1, 'A healthy BMI is…', '18.5 – 24.9', ['30 – 39.9', '5 – 10', '40 +'], 'Below 18.5 = underweight; 25+ = overweight.'),
        mt(2, 'Match the BMI to its category', [['Under 18.5', 'Underweight'], ['18.5 – 24.9', 'Healthy'], ['25 – 29.9', 'Overweight'], ['30 – 39.9', 'Obese']]),
        mc(2, 'Someone has a BMI of 27. They are…', 'Overweight', ['Healthy', 'Underweight', 'Severely obese'], '25 to 29.9 = overweight.'),
        mc(2, 'Being obese increases the risk of…', 'Type 2 diabetes and heart disease', ['Asthma only', 'Short-sightedness', 'Colds'], 'Also joint problems, some cancers, and low self-esteem.'),
        mc(3, 'Someone weighs 80 kg and is 2 m tall. Their BMI is…', '20', ['40', '160', '82'], '80 ÷ 2 ÷ 2 = 20. That\'s healthy.'),
        mc(3, 'A BMI of 17 is underweight. A possible risk is…', 'A weak immune system and brittle bones', ['High blood pressure', 'Type 2 diabetes', 'None'], 'Being underweight can mean poor nutrition.'),
        mc(3, 'A weakness of BMI is…', 'It doesn\'t tell muscle from fat', ['It is too hard to measure', 'It uses blood', 'It only works on children'], 'A very muscular athlete could show as "overweight".'),
      ]),
      LS('h-life', 'Lifestyle numbers', '🚭', ['Alcohol: no more than 14 units a week.', 'Adults: 150 minutes of moderate exercise a week.'], [
        mc(1, 'The UK guideline for alcohol is no more than…', '14 units a week', ['50 units a week', '2 units a month', '100 units a week'], 'Spread over 3 or more days, with some alcohol-free days.'),
        mc(1, 'Adults should do at least how much moderate exercise a week?', '150 minutes', ['15 minutes', '10 hours a day', '5 minutes'], 'e.g. 30 minutes, 5 days a week.'),
        mc(1, 'Smoking greatly increases the risk of…', 'Lung cancer', ['Broken legs', 'Short-sightedness', 'Flu only'], 'Also heart disease, stroke and breathing problems (COPD).'),
        mc(2, 'Young people (5–18) should be active for…', 'An average of 60 minutes a day', ['10 minutes a week', '5 hours a day', 'Never'], 'Children need more activity than adults.'),
        mc(2, 'An "inactive" lifestyle can lead to…', 'Weight gain and heart disease', ['Stronger muscles', 'Better sleep', 'Lower blood pressure'], 'Inactivity is a big health risk.'),
        mc(2, 'Someone drinks 28 units a week. That is…', 'Double the recommended limit', ['Healthy', 'Half the limit', 'Exactly the limit'], '28 is twice 14.'),
        mc(3, 'How can smoking affect SOCIAL wellbeing?', 'Friends or places may avoid the smell/smoke', ['It makes more friends', 'No effect', 'It improves fitness'], 'Link lifestyle choices to PIES.'),
        mc(3, 'Smoking also affects economic wellbeing because…', 'Cigarettes cost a lot of money', ['It earns you money', 'It is free', 'It lowers taxes'], 'Money spent on smoking can\'t be spent on healthy food or activities.'),
      ]),
    ] },
    { id: 'hC3c', title: 'C3 · Making a health plan', emoji: '📝', blurb: 'Recommend changes, set SMART targets, suggest support, spot obstacles.', tag: 'exam', tagText: 'EXAM · May', lessons: [
      LS('h-smart', 'SMART targets & plans', '🎯', ['SMART = Specific, Measurable, Achievable, Realistic, Time-related.', 'Person-centred = built around what THEY need and want.'], [
        mc(1, 'What does the S in SMART stand for?', 'Specific', ['Simple', 'Speedy', 'Safe'], 'Clear and exact — not vague.'),
        mc(1, 'What does the T in SMART stand for?', 'Time-related (has a deadline)', ['Tough', 'Talking', 'Total'], 'e.g. "within 3 months".'),
        mc(1, '"Person-centred" means the plan…', 'Is built around the individual\'s needs and wishes', ['Is the same for everyone', 'Is made by the doctor only', 'Ignores the person'], 'The person should be involved in decisions.'),
        mc(2, 'Which is a SMART target?', 'Walk for 30 minutes, 5 days a week, for the next 8 weeks', ['Get fitter', 'Exercise more sometime', 'Be healthy'], 'It\'s specific, measurable and has a time limit.'),
        mc(2, 'Which is NOT SMART?', 'Eat better', ['Cut down to 5 cigarettes a day within 4 weeks', 'Lose 2 kg in 6 weeks', 'Drink no more than 14 units a week from now on'], '"Eat better" is vague — how much? by when?'),
        od(2, 'Order the steps of a health improvement plan', ['Assess their health (measurements)', 'Set SMART targets', 'Recommend actions and support', 'Think about possible obstacles'], 'The exam often asks you to do parts of this for a person in a case study.'),
        mc(3, 'Why should targets be short-term AND long-term?', 'Small wins keep motivation up while working to a bigger goal', ['To confuse people', 'Because the law says so', 'There\'s no reason'], 'e.g. short-term: cut down smoking; long-term: stop completely.'),
        mc(3, 'Why involve the person in making their plan?', 'They are more likely to stick to it', ['It makes it faster', 'It isn\'t allowed', 'To make it harder'], 'Person-centred = empowering and more motivating.'),
      ]),
      LS('h-support', 'Support & obstacles', '🤝', ['Formal support = professionals (GP, nurse).', 'Informal = family and friends.  Voluntary = charities.'], [
        mc(1, 'A GP is an example of…', 'Formal support', ['Informal support', 'Voluntary support', 'No support'], 'Formal = paid, trained professionals.'),
        mc(1, 'A best friend helping you quit smoking is…', 'Informal support', ['Formal support', 'Voluntary support', 'Tertiary care'], 'Informal = family, friends, neighbours.'),
        mt(2, 'Match the support type', [['Formal', 'practice nurse'], ['Informal', 'sister'], ['Voluntary', 'charity group']]),
        mc(2, 'Which is an EMOTIONAL obstacle to a health plan?', 'Low motivation or low self-esteem', ['No gym nearby', 'No money', 'Bad weather'], 'Emotional/psychological obstacles come from how the person feels.'),
        mc(2, 'Which obstacle is about time?', 'Working long hours and caring for children', ['Low self-esteem', 'Addiction', 'Disability'], 'Time constraints make it hard to exercise or cook.'),
        mc(2, 'Which is a FINANCIAL obstacle?', 'Can\'t afford gym membership', ['Feeling shy', 'Living far away', 'Bad eyesight'], 'Money (resources) can stop people following plans.'),
        mc(3, 'Someone lives in a village with no bus to the gym. This is a…', 'Geographical barrier', ['Financial barrier', 'Emotional barrier', 'Language barrier'], 'Distance and transport are geographical barriers.'),
        mc(3, 'A target that is too hard (unachievable) can…', 'Make the person give up', ['Help them try harder forever', 'Make them richer', 'Have no effect'], 'That\'s why the A in SMART matters.'),
        mc(3, 'Addiction is an obstacle because…', 'It makes stopping smoking or drinking very hard', ['It gives more energy', 'It saves time', 'It is always easy to beat'], 'Addicted people may need specialist support (e.g. stop-smoking services).'),
      ]),
    ] },
    { id: 'hC1', title: 'C1 · Growing up & life events', emoji: '👶', blurb: 'Component 1 (coursework, Year 10). The exam builds on it, so keep it fresh.', tag: 'cw', tagText: 'Coursework recap', lessons: [
      LS('h-stages', 'Life stages', '📅', ['Infancy 0–2 · Early childhood 3–8 · Adolescence 9–18', 'Early adulthood 19–45 · Middle 46–65 · Later 65+'], [
        od(1, 'Put the life stages in order', ['Infancy', 'Early childhood', 'Adolescence', 'Early adulthood', 'Middle adulthood', 'Later adulthood'], 'From birth to old age.'),
        mt(1, 'Match the life stage to its ages', [['Infancy', '0–2'], ['Early childhood', '3–8'], ['Adolescence', '9–18'], ['Later adulthood', '65+']]),
        mc(2, 'Early adulthood is…', '19–45 years', ['9–18 years', '46–65 years', '0–2 years'], 'Often: work, relationships, maybe children.'),
        mc(2, 'Middle adulthood is…', '46–65 years', ['19–45 years', '65+ years', '3–8 years'], 'Women go through the menopause in this stage.'),
        mc(2, 'Puberty happens in…', 'Adolescence', ['Infancy', 'Later adulthood', 'Middle adulthood'], 'Hormones cause body changes.'),
        mc(3, 'The menopause usually happens in…', 'Middle adulthood', ['Adolescence', 'Early childhood', 'Infancy'], 'Periods stop; can affect mood and bones.'),
      ]),
      LS('h-pies-dev', 'Development (PIES)', '🧸', ['Gross motor = big movements (walking).', 'Fine motor = small, careful movements (holding a pencil).'], [
        mc(1, 'Walking and running are…', 'Gross motor skills', ['Fine motor skills', 'Intellectual skills', 'Social skills'], 'Gross = big muscles.'),
        mc(1, 'Picking up a raisin with finger and thumb is…', 'A fine motor skill', ['A gross motor skill', 'Emotional development', 'Social development'], 'Fine = small, precise movements.'),
        mc(2, 'A baby forming a close bond with a parent is called…', 'Attachment', ['Puberty', 'Independence', 'Menopause'], 'Part of emotional development in infancy.'),
        mc(2, 'Learning to talk is part of…', 'Intellectual development (language)', ['Physical development', 'Economic development', 'Gross motor skills'], 'Language, memory and problem solving are intellectual.'),
        mc(2, 'Making friends at school is…', 'Social development', ['Physical development', 'Fine motor skills', 'Genetic inheritance'], 'Relationships = social.'),
        mc(3, 'In later adulthood, a common PHYSICAL change is…', 'Weaker bones and slower movement', ['Growth spurts', 'Puberty', 'Learning to walk'], 'Ageing: less mobility, sight and hearing may weaken.'),
        mc(3, 'Self-image and self-esteem are part of…', 'Emotional development', ['Physical development', 'Intellectual development', 'Gross motor skills'], 'How you see and value yourself.'),
      ]),
      LS('h-events', 'Life events & coping', '🌦️', ['Life events: physical (injury), relationships (divorce), life circumstances (moving house).', 'Support: family & friends, professionals, charities.'], [
        mc(1, 'A broken leg from a car accident is a…', 'Physical life event', ['Relationship change', 'Life circumstance change', 'Economic factor'], 'Physical events: accidents, injuries, ill health.'),
        mc(1, 'Moving to a new school is a change in…', 'Life circumstances', ['Relationships', 'Physical health', 'Genes'], 'Moving house, school or job; retirement; redundancy.'),
        mc(2, 'Bereavement means…', 'Someone close to you has died', ['Getting married', 'Starting a job', 'Having a baby'], 'A relationship change that causes grief.'),
        mt(2, 'Match the support', [['Emotional support', 'someone to listen'], ['Information & advice', 'leaflet or helpline'], ['Practical help', 'lift to hospital']]),
        mc(2, 'Which is a professional source of support?', 'A counsellor', ['A grandparent', 'A neighbour', 'A classmate'], 'Professionals are trained and paid.'),
        mc(3, 'Why do people cope differently with the same life event?', 'Different personalities, support and resilience', ['They all cope the same', 'Only age matters', 'It\'s random'], 'Having support makes a big difference.'),
        mc(3, 'A charity like Cruse helps people with…', 'Bereavement (grief)', ['Broken bones', 'Money problems only', 'Homework'], 'Voluntary and faith groups offer lots of support.'),
      ]),
    ] },
    { id: 'hC2', title: 'C2 · Services & care values', emoji: '🏥', blurb: 'Component 2 (coursework, Year 10). Care values and services often come up again.', tag: 'cw', tagText: 'Coursework recap', lessons: [
      LS('h-services', 'Care services', '🏥', ['Primary = first contact (GP, dentist).', 'Secondary = specialist (hospital).  Tertiary = very specialist (e.g. cancer care).'], [
        mc(1, 'A GP is an example of…', 'Primary care', ['Secondary care', 'Tertiary care', 'Social care'], 'Primary care = the first place you go.'),
        mc(1, 'Hospital specialist treatment after a GP referral is…', 'Secondary care', ['Primary care', 'Informal care', 'Voluntary care'], 'Secondary = specialist, usually by referral.'),
        mt(2, 'Match the care type', [['Primary', 'GP / dentist'], ['Secondary', 'hospital specialist'], ['Tertiary', 'cancer or burns unit'], ['Allied health', 'physiotherapist']]),
        mc(2, 'A physiotherapist, speech therapist and dietitian are…', 'Allied health professionals', ['Informal carers', 'Primary school teachers', 'Voluntary workers'], 'They support recovery and independence.'),
        mc(2, 'Care given in someone\'s own home is…', 'Domiciliary care', ['Residential care', 'Tertiary care', 'Respite care'], 'Domiciliary = at home.'),
        mc(3, 'Short-term care that gives a family carer a break is…', 'Respite care', ['Primary care', 'Domiciliary care', 'Foster care'], 'Respite = a rest for the carer.'),
        mc(3, 'A relative who looks after someone without being paid is an…', 'Informal carer', ['Allied health professional', 'Formal carer', 'Tertiary carer'], 'Informal = family, friends, neighbours.'),
      ]),
      LS('h-barriers', 'Barriers to care', '🚧', ['Barriers stop people getting the care they need.', 'e.g. physical, sensory, language, geographical, financial.'], [
        mc(1, 'Stairs with no lift for a wheelchair user are a…', 'Physical barrier', ['Language barrier', 'Financial barrier', 'Cultural barrier'], 'Physical barriers stop people getting in/around.'),
        mc(1, 'Not speaking English well enough to explain symptoms is a…', 'Language barrier', ['Physical barrier', 'Geographical barrier', 'Financial barrier'], 'Interpreters and translated leaflets help.'),
        mc(2, 'A deaf person who can\'t hear their name called is facing a…', 'Sensory barrier', ['Financial barrier', 'Geographical barrier', 'Physical barrier'], 'Sensory = sight or hearing. Fix: visual screens, BSL.'),
        mc(2, 'Living far from the hospital with no transport is a…', 'Geographical barrier', ['Language barrier', 'Sensory barrier', 'Cultural barrier'], 'Distance/location.'),
        mc(2, 'Not being able to pay for prescriptions or dental care is a…', 'Financial barrier', ['Physical barrier', 'Language barrier', 'Sensory barrier'], 'Money stops access.'),
        mc(3, 'Feeling embarrassed or scared to see a doctor is a…', 'Psychological barrier', ['Geographical barrier', 'Financial barrier', 'Physical barrier'], 'Also social and cultural barriers — e.g. wanting a doctor of the same gender.'),
        mc(3, 'Long waiting lists caused by too few staff are a…', 'Resource barrier (for the service)', ['Language barrier', 'Sensory barrier', 'Physical barrier'], 'Services may lack staff, money or equipment.'),
      ]),
      LS('h-values', 'Care values', '💞', ['Care values: empowerment, respect, confidentiality, dignity, communication, safeguarding, anti-discrimination.'], [
        mc(1, 'Keeping someone\'s private information safe is…', 'Confidentiality', ['Empowerment', 'Safeguarding', 'Dignity'], 'Only share on a need-to-know basis.'),
        mc(1, 'Closing curtains when helping someone get dressed preserves their…', 'Dignity', ['Confidentiality', 'Independence', 'Money'], 'Dignity = respecting privacy and self-respect.'),
        mc(1, 'Letting someone choose what to wear is…', 'Empowering them', ['Safeguarding', 'Discriminating', 'Ignoring them'], 'Empowerment = giving people choice and control.'),
        mc(2, 'Protecting people from harm and abuse is…', 'Safeguarding', ['Confidentiality', 'Empowerment', 'Dignity'], 'Carers have a duty of care.'),
        mc(2, 'Treating everyone fairly, whatever their race, religion or disability, is…', 'Promoting anti-discriminatory practice', ['Confidentiality', 'Respite', 'Domiciliary care'], 'Challenge any discrimination you see.'),
        mt(2, 'Match the care value', [['Confidentiality', 'keep info private'], ['Dignity', 'close the door'], ['Empowerment', 'let them choose'], ['Safeguarding', 'protect from harm']]),
        mc(3, 'Effective communication includes…', 'Speaking clearly, listening and using body language', ['Shouting so they hear', 'Using lots of jargon', 'Talking over them'], 'Also: using the right language, eye contact, patience.'),
        mc(3, 'When CAN confidential information be shared?', 'If someone is at risk of harm', ['Whenever you want', 'Never, even in danger', 'On social media'], 'Safeguarding comes first.'),
      ]),
    ] },
  ],
});
